### ISSUE TITLE
Style code inside a `table` element the same as code outside a table

### ISSUE THREAD

**Issue by nnooney** [tailwindlabs/tailwindcss-typography#104]
Context: when using Hugo to generate code, it's possible to specify two styles of line numbering (linenos=table and linenos=inline). These generate significantly different HTML based on the style chosen:

linenos=table
```html
<div class="highlight">
  <div class="chroma">
    <table class="lntable">
      <tbody>
        <tr>
          <td class="lntd"><pre class="chroma"><code>...</code></pre></td>
          <td class="lntd"><pre class="chroma"><code>...</code></pre></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
```

linenos=inline
```html
<div class="highlight">
  <pre class="chroma">
    <code>...</code>
  </pre>
</div>
```

Tailwind's typography for tables results in strong interference with the code markup (beginning with `.pre`). To work around this, I've had to add the following changes to my config to override this:

```
module.exports = {
  theme: {
    extend: {
      typography: (theme) => ({
        DEFAULT: {
          css: {
            table: {
              pre: {
                margin: 0,
                fontSize: '1em',
              }
            },
            tbody: {
              td: {
                '&:first-child': { pre: { paddingRight: 0, }, },
                '&:last-child': { pre: { paddingLeft: 0, }, },
              },
            },
          }
        }
      }),
    },
  },
}
```

It would be nice if the styling for code within tables was the same as code without tables, so that Hugo generated code looks similar with both styles of line numbers.

**Comment by Rasmussen-7876** [comment]
Note that the number of rows in a table is equal to the number of TR elements should format the table according to HTML attributes and style sheet specification.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

I could be wrong, but I don't think this is an issue anymore, here is an example of both your examples: https://play.tailwindcss.com/5whNt4pjpH and they look the same to me unless I'm missing something.

If this is still an issue for you, could you open a new issue with a bit more information and a reproduction repo? Since this is a visual issue, could you add screenshots of actual and expected behaviour?
