### ISSUE TITLE
Bug: Prose class streching Nextjs Image Component

### ISSUE THREAD

**Issue by impulse** [tailwindlabs/tailwindcss-typography#105]
![ezgif-3-aed2539c391d](https://user-images.githubusercontent.com/8146736/101288235-c1086480-37f5-11eb-97e2-98fbd9f2863c.gif)

Reproduction available here:
https://github.com/impulse/nextjs-tailwind-ts/tree/nextjs-image-prose-issue

**Comment by leerob** [comment]
https://github.com/vercel/next.js/issues/19964

**Comment by michrome** [comment]
Also https://github.com/vercel/next.js/issues/19817 😀

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This seems an issue that occurs based on the way that Next.js outputs the image(s).
I don't think that we want to account for this use case.
This seems something that you want to have in **your** codebase itself.

**Comment by leerob** [comment]
We're also thinking about adding "defensive" styling into `next/image` to prevent this and help users fall into the pit of success!
