### ISSUE TITLE
Feature request: pick which element you want to style

### ISSUE THREAD

**Issue by htulipe** [tailwindlabs/tailwindcss-typography#106]
Hi, here's a feature request:

I'm rendering documents that never contain `table` nor `h` above 2, I'd like to be able to tell that to the plugin so that it does not generated css classes for those elements. I was thinking of a whitelist (just like the one that can disable size modifiers)

Thanks

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

If you are using the tailwindcss purge option https://tailwindcss.com/docs/optimizing-for-production then the styles should not be included in the end.

If you want to be explicit about certain things, you can apply something like this:

```js
module.exports = {
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            blockquote: null // Explicitly set to null
          }
        }
      }
    }
  }
}
```

**Comment by htulipe** [comment]
Hey, thanks for replying. 

I thought about the second option but it'd be more effective to have an opt-in approach (I'm using a very small subset of what the plugin is styling).

Are you sure about the purge option behavior ? I'm using it and the typography styles are not being removed (while it works for "normal" tailwind classes). I'm only applying the "prose" class to my top level container. I'm building the DOM using React if that can be relevant.

**Comment by htulipe** [comment]
Could it be that, since the plugin generates CSS selector on tag names (and not class), the purge option won't work as expected ? For instance if somewhere in my codebase (not related to typography stuff) I have an "h3" JSX tag, the purge process, which is ran on the entire codebase, will assume it needs to keep "h3" CSS selector ?
