### ISSUE TITLE
The @tailwindcss/typography package on npm contains the demo folder

### ISSUE THREAD

**Issue by beeman** [tailwindlabs/tailwindcss-typography#120]
The [package that is on npm](https://unpkg.com/browse/@tailwindcss/typography@0.3.1/demo/) still contains the demo which takes a considerable amount of disk space in node_modules. 

![image](https://user-images.githubusercontent.com/36491/103301244-f5bfa400-49ce-11eb-988d-8dfb6a2a26ca.png)

![image](https://user-images.githubusercontent.com/36491/103301322-2273bb80-49cf-11eb-9fe2-ba20255a2013.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We fixed this in this PR: https://github.com/tailwindlabs/tailwindcss-typography/pull/112
I will make sure to release a new version today!

**Comment by beeman** [comment]
Thanks for the fix @RobinMalfait! 🙏
