### ISSUE TITLE
Prose classes missing in rendered CSS (via Laravel Mix)

### ISSUE THREAD

**Issue by marcreichel** [tailwindlabs/tailwindcss-typography#121]
I've installed the package and referenced it in my `tailwind.config.js` but only the `.max-w-prose`-classes are in my final css. All other classes are missing?!

Used versions:
| Package | Version |
|---------|---------|
| Laravel | 8.20.1 |
| Laravel Mix | 5.0.9 |
| @tailwindcss/typography | 0.3.1 |
| @tailwindcss/postcss7-compat | 2.0.2 |

Here is my `tailwind.config.js`:
```javascript
module.exports = {
    purge: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {},
    },
    variants: {
        extend: {},
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
    ],
}
```

And my `webpack.mix.js`:
```javascript
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/assets/js')
    .postCss('resources/css/app.css', 'public/assets/css', [
        require('tailwindcss'),
    ])
    .version();
```

What am I doing wrong?

If you need more information please let me know.

**Comment by mattradford** [comment]
Same for me

| Package | Version |
| --------------- | --------------- |
| Laravel Mix | 6.0.5 |
| tailwindcss | 2.0.2 |
| @tailwindcss/typography | 0.3.1 |

```
module.exports = {
  // important: "html",
  theme: {
    container: {
      center: true,
    },
    future: {
      // https://tailwindcss.com/docs/upcoming-changes
      purgeLayersByDefault: true,
    },
    typography: {
      default: {
        css: {
          color: "#333",
        },
      },
    },
    editorColorPalette: {
      primary: "blue",
      secondary: "#ccc",
    },
    editorFontSizes: {
      small: "16px",
      medium: "22px",
    },
    extend: {},
  },
  variants: {},
  plugins: [
    require("@tailwindcss/typography"),
    require("@mattrad/tailwindcss-wordpress"),
    ({ addComponents, theme }) => {
      addComponents({
        ".content > :not(.alignwide):not(.alignfull):not(.alignleft):not(.alignright):not(.wp-block-separator):not(.woocommerce)": {
          "@apply mx-auto": {},
          "@screen sm": {
            maxWidth: theme("screens.sm"),
          },
        },
        ".content > .wp-block-button": {
          "@apply mx-auto": {},
          "@screen sm": {
            maxWidth: theme("screens.sm"),
          },
        },
      });
    },
  ],
};

This is compiled output I get:

```
.prose {
}

.prose-sm {
}

.prose-lg {
}

.prose-xl {
}

.prose-2xl {
}

.prose-red {
}

.prose-yellow {
}

.prose-green {
}

.prose-blue {
}

.prose-indigo {
}

.prose-purple {
}

.prose-pink {
}
```
```

**Comment by mattradford** [comment]
FWIW @marcreichel, I stripped my `tailwind.config.js` back to the following:

```
module.exports = {
  plugins: [
    require("@tailwindcss/typography")
  ],
};
```
Then  all `prose` classes were generated as expected.

**Comment by mattradford** [comment]
@marcreichel I've got a bit more for you. My Tailwind config had the following:

```
  theme: {
    typography: {
      default: {
        css: {
          color: "#333",
        },
      },
    },
    extend: {},
  },
```

It now works with the following config:

```
theme: {
    extend: {
      typography: {
          DEFAULT: {
            css: {
              color: "#333",
            },
          },
        },
    },
},
```

**Comment by marcreichel** [comment]
@mattradford Hm, but I don't even manipulate the typography plugin via `theme` or `theme.extend`. Also it should not be the solution to strip down your tailwind config in order to make this plugin work I guess 😄 
In my original `tailwind.config.js` I just extend the color palette and setup purging. These settings should not interfere this plugin (I hope).

**Comment by marcreichel** [comment]
This is my full `tailwind.config.js`:

```javascript
const colors = require('tailwindcss/colors');

module.exports = {
    purge: {
        enabled: false,
        content: [
            './resources/**/*.blade.php',
            './resources/**/*.js',
            './resources/**/*.vue',
        ],
    },
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            colors: {
                primary: colors.green,
                rose: colors.rose,
            },
            fontFamily: {
                headers: ['Vollkorn', 'serif'],
            }
        },
    },
    variants: {
        extend: {},
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
    ],
}
```

**Comment by mattradford** [comment]
> ...I don't even manipulate the typography plugin...

You're quite right! This is still an issue, but my results could be a workaround for now. Have you tried adding in some config for the plugin to see if that makes a difference?

**Comment by marcreichel** [comment]
Yes, I've added

```javascript
module.exports = {
    // ...
    theme: {
        extend: {
            typography: {
                DEFAULT: {
                    css: {
                        color: '#333',
                    },
                },
            },
            // ...
        },
    },
    // ...
};
```

as you suggested but this makes no difference.

**Comment by marcreichel** [comment]
I've even disabled purging completely to check if those classes are purged away ... for some reason ... in dev environment 😄 
But they are not. Which is good I think 😄 

In the tailwind Playground the plugin is working though ... So I think it is a problem with Laravel Mix?! But I cannot see what the problem should be.

**Comment by mt-dev44** [comment]
I was having the same problem! I believe I got it working with the following: 

```
const mix = require('laravel-mix');
const tailwindcss = require('tailwindcss');

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        tailwindcss('./tailwindcss.config.js')
    ])
    .version();
```

I am using a default tailwind config based on the install in larevel guide.

**Comment by marcreichel** [comment]
@mt-dev44 Sadly, this did not change anything for me.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

In this thread are multiple issues happening, so I am going to focus on the main issue that @marcreichel reported.

### Why does `max-w-prose` exist?

This is because `max-w-prose` is a class from tailwind itself and not from the `typography` plugin. While it shares a name, the `max-w-prose` is more generic and indicates an ideal reading length for content. The `max-w-prose` can be found here: https://tailwindcss.com/docs/max-width#prose

### For your second question, why don't I see `prose` related classes?

My current assumption is that `laravel-mix` (or maybe you do it in one of the scripts) is adding a `NODE_ENV=production`. This tells tailwindcss to start purging. A common approach with the `prose` class is that the content is coming from a database and therefore the `prose` class cannot be found in the files you listed in your config. Therefore it is purged.

The first thing you can try is by removing the purge options in your tailwind config. This is just to make sure that if we are *not* purging that everything works as expected. (This is a temporary thing just to validate some assumptions)

- If the `prose` class is available after you do this, then we have to look into making sure that we safelist the `prose` class. Because we don't want it to get purged even though it is not used (yet). See: https://tailwindcss.com/docs/optimizing-for-production#purge-css-options
- If the `prose` class is *not* available after you do this, then you have to double check that your `typography` plugin is installed (inside node_modules). We also have to double check that your `tailwind.config.js` is actually used. A quick test for this is by putting a `console.log('I am used')` in the `tailwind.config.js` file and if you run your mix command you should see that log in your terminal output.

I'll keep this issue open and wait for your response!

**Comment by marcreichel** [comment]
@RobinMalfait Thank you for your answer.

I disabled purging completely by setting `purge` in my `tailwind.config.js` to `false` which did not make any difference.
Also the files containing the `prose` related classes are static files and are not coming from a database. The files are referenced in the `purge` config via the `content` array as well (as you can see in one of my previous comments and initial issue).
Also the `tailwind.config.js` is used as I am getting the other settings (like additional colors etc.) in my rendered CSS. But I added the `console.log()` like you mentioned and I can see the line in my console as expected.
The CSS is not purged (due to some `NODE_ENV=production`) as well as the rendered CSS is currently a whopping 4.25 MB in size which seems unpurged to me (hopefully :D).

Little side note: The `@tailwindcss/forms` plugin is working just fine and the styles are in my rendered and purged CSS and unpurged CSS as well.

Removing the `purge` option completely did not make any difference either.

**Comment by adamwathan** [comment]
If you provide a reproduction it will be a lot easier to troubleshoot, guessing about what could be going wrong back and forth is really inefficient compared to just cloning a repo and playing with it 👍🏻

**Comment by marcreichel** [comment]
Well nevermind. Was about to create a new repository (as you requested @adamwathan) with everything setup and it just worked. In the original project I was still using the tailwind postcss 7 compat build with autoprefixer 9 and laravel-mix 5.
The new project with postcss 8, the "correct" tailwindcss build and laravel-mix 6 works fine though.

Nevertheless I could not get the original project to work with all dependencies updated nor reproduce the "error" on the new repository with the old dependencies. Just spent about 2 hours figuring out what the differences are without success.
So I created a fresh Laravel project and migrated all work I've done so far over from the "old" original project .. and it is working. Strangely enough.

Closing this issue as it's seemed to be fixed magically (I guess) with the new versions 🤷🏼‍♂️ 💪🏼

**Comment by ilabsllc** [comment]
I am seeing similar behavior with the latest versions. I am not able to repro this in a new simple project I created to file a bug. 

The only class available is prose-xl and I can't find any other prose- class. I am using it with the next JS project.

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
```

Any ideas on how to debug this.
