### ISSUE TITLE
Markdown inline code not rendering properly

### ISSUE THREAD

**Issue by gcman105** [tailwindlabs/tailwindcss-typography#123]
## Below is the markdown:

![CleanShot 2021-01-02 at 21 31 06](https://user-images.githubusercontent.com/460778/103466109-19257e80-4d42-11eb-85c7-a6e0eb22ca43.png)

## Which renders:

![CleanShot 2021-01-02 at 21 28 34](https://user-images.githubusercontent.com/460778/103466113-23477d00-4d42-11eb-9305-a1f6c6dd6b90.png)

**Comment by CodeAndWeb** [comment]
I came across the same issue... wondering why they intentionally add the ticks. But you can get rid of them the following way in your config:

    theme: {
        extend: {
            typography: {
                DEFAULT: {
                    css: {
                        "code::before": {content: ''},
                        "code::after": {content: ''}
                    }
                }
            }
        }
    },

**Comment by gcman105** [comment]
@CodeAndWeb Thanks. That works a treat.

**Comment by 4044ever** [comment]
Just want to add that @CodeAndWeb snippet also works in TailwindCSS 3.0
