### ISSUE TITLE
UNPKG CDN provides resource with wrong MIME type

### ISSUE THREAD

**Issue by badazz91** [tailwindlabs/tailwindcss-typography#127]
Hello guys,

when including tailwind-typography via the CDN it produces the following warning in the browser:

`Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://unpkg.com/@tailwindcss/typography@0.2.x/dist/typography.min.css".`

Should the MIME type not be `text/css` instead.

**Comment by adamwathan** [comment]
Hey! I just checked and it comes through as text/css when I visit that URL:

![image](https://user-images.githubusercontent.com/4323180/104210337-c19da780-5400-11eb-8acf-1a40e3881c48.png)

Either way if this is an issue in certain circumstances it's something UNPKG would have to fix, nothing we can do on our end.

If you're having issues with UNPKG you can try other CDNs like jsDelivr:

https://cdn.jsdelivr.net/npm/@tailwindcss/typography@0.3.1/dist/typography.min.css

We don't actually deliberately host any CDN files, these are all just services that automatically mirror content on npm behind a CDN 👍

**Comment by badazz91** [comment]
@adamwathan switch to the jsDelivr CDN resolved the warning. Seems that only UNPKG sends the wrong MIME type.

Thanks for the help!
