### ISSUE TITLE
Paragraph styling

### ISSUE THREAD

**Issue by barrycenter** [tailwindlabs/tailwindcss-typography#128]
Paragraph styles have a top margin which messes up many layouts. Generally speaking, I'd like to see only bottom margins used on every element since a document flows downward and it allows the tops of the elements to be placed properly at the tops of their containers.

With paragraphs, it's especially frustrating because it's common to use prose to format user-provided content and most people only use paragraph tags when the entry is multiple paragraphs and no tag when it's just one paragraph. However, when these are rendered in a common component, the items with paragraph tags are a full line height further from the top of the div than those without; making the instances render non-uniformly.

This is especially an issue when laying text in multicolumn layouts since the first paragraph will always have a margin at the top and the remaining columns will render at the top of their respective columns like this:

<img width="1106" alt="Screen Shot 2021-01-12 at 1 59 29 AM" src="https://user-images.githubusercontent.com/682266/104280399-d9654200-5479-11eb-89fe-d8049b282492.png">

Ideally, the first paragraph would be at the top of the column, too. Is there any sensible way to override this?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

We currently have code where we remove margins from the first element. Here is an example of that behaviour: https://play.tailwindcss.com/scIFhPMLx8
Here is the code where we remove the top and bottom margin of the first and last child respectively: https://github.com/tailwindlabs/tailwindcss-typography/blob/446eed16e3c63119e840ec6951c667577b69d811/src/styles.js#L348-L353

For your specific use case where you have a multi-column layout. You could do something like this: https://play.tailwindcss.com/bUjDngi1C0

Essentially what I did is add a wrapper component with a `multicolumns` class. Then inside the config, I made sure to remove the marginTop/marginBottom of paragraphs. Inside the config it's essentially pure css, with the difference that the key is the selector and the value is an object with properties. This also allows you to use the `theme()` function if you want to.
