### ISSUE TITLE
Unintentional spacing in code blocks using Mozilla Firefox

### ISSUE THREAD

**Issue by weleo** [tailwindlabs/tailwindcss-typography#130]
Unintentional spacing in code blocks is rendered using Firefox, while it works as intended on Safari and Chrome.

**[Example](https://content.nuxtjs.org/installation) with Firefox:**

![Screenshot 2021-01-14 at 00 57 05](https://user-images.githubusercontent.com/57549150/104527645-828c7380-5605-11eb-9227-4e9d3d80789c.png)

A quick fix in `tailwind.config.js` is to overwrite the default `'pre code::after':  {  content: 'none'  }` with **_the default_** (and I have no idea why):

```
module.exports = {
  theme: {
    extend: {
      typography: theme => ({
        DEFAULT: {
          css: [
             {
              'pre code::after': {
                content: 'none'
              }
            }
          ]
        }
      })
    }
  },
  plugins: [require('@tailwindcss/typography')]
}
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This was fixed last week https://github.com/tailwindlabs/tailwindcss-typography/pull/125 but I'll make sure to publish a new release today!
