### ISSUE TITLE
How to stop `inline code blocks` from rendering with the backticks?

### ISSUE THREAD

**Issue by MichaelScoggins** [tailwindlabs/tailwindcss-typography#135]
When I use the prose classname in my sanity richText, it renders the backticks onto the page when I do not want this. I just want it to show in consolas or whatever font for the inline code.

**Comment by jasperro** [comment]
Why was this closed? The theming of the code blocks was changed in 47fe7326913f66a45a4f5b8249b81cc091ec070d. This looks very inconsistent with the `<pre>` theming. @adamwathan, could this be changed back to how it was before, or is there a way to override this in the tailwind configuration?

**Comment by adamwathan** [comment]
This was changed before the library was even released. You can override the styles in your config:

https://github.com/tailwindlabs/tailwindcss-typography/issues/18

**Comment by jasperro** [comment]
Thanks! That worked perfectly.

**Comment by TeemuKoivisto** [comment]
So the answer in #18 works but just to save somebody's time, I'm going to paste it here for convenience's sake.

```js
module.exports = {
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            'code::before': {
              content: '""'
            },
            'code::after': {
              content: '""'
            }
          }
        }
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
```

**Comment by vidhanio** [comment]
For future reference for Tailwind v3,
```
class="... prose-code:before:content-none prose-code:after:content-none"
```
