### ISSUE TITLE
What can be done to long links in small screen size?

### ISSUE THREAD

**Issue by vinliao** [tailwindlabs/tailwindcss-typography#138]
I'm not quite sure where to go after encountering this.

![Screenshot from 2021-02-08 22-17-50](https://user-images.githubusercontent.com/34117807/107240626-b324c900-6a5c-11eb-85dc-856dd1e1f350.png)

Have any of you solved this problem?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you try and reproduce it on https://play.tailwindcss.com and share it?
When I try to reproduce this issue, it seems to wrap correctly: https://play.tailwindcss.com/rgrt88vyFv?size=300x720

**Comment by vinliao** [comment]
The no-wrap problem is pretty dramatic on my local machine, but I can't seem to replicate it on https://play.tailwindcss.com

![Screenshot from 2021-02-13 19-41-19](https://user-images.githubusercontent.com/34117807/107850518-952cdf00-6e35-11eb-9b88-b8ac381bf2ca.png)

And to be quite honest with you, this is not a truly urgent issue; it may look broken on 197 px width, but who the hell has a screen with 197 px width? 

It actually looks decent on normal screens. I don't even remember why I opened this issue in the first place.

**Comment by RobinMalfait** [comment]
I think this is also a browser "issue", here are some examples:

| Safari | Firefox Nightly | Brave |
| -- | -- | -- |
| <img width="312" alt="image" src="https://user-images.githubusercontent.com/1834413/108492174-202e2f00-72a5-11eb-8fa2-b5d8ebbcb50a.png"> | <img width="312" alt="image" src="https://user-images.githubusercontent.com/1834413/108492204-29b79700-72a5-11eb-8fa9-c676b97ea894.png"> | <img width="310" alt="image" src="https://user-images.githubusercontent.com/1834413/108492279-3e942a80-72a5-11eb-9237-195bf473c148.png"> |


---

As you mentioned, this is probably not a real issue issue that will occur in production. Going to close this, feel free to open a new issue when other issues occur.

**Comment by derekphilipau** [comment]
In my experience this issue often arises when rendering markdown, luckily tailwind makes it easy to accomodate for: `class="prose break-words"`

https://tailwindcss.com/docs/word-break

**Comment by namjul** [comment]
The difference is the hyphen in the links. long texts that don't have [break opportunities](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#suggesting_line_break_opportunities) won't wrap by default. I think this question is still relevant in the context of what tailwindcss-typography might provide for these situations. For anyone coming here `overflow-wrap` is your friend.
