### ISSUE TITLE
Allowing override of root CSS selector

### ISSUE THREAD

**Issue by pierreminik** [tailwindlabs/tailwindcss-typography#140]
Hi,

Using this plugin with a CMS like WordPress that is block based causes some issues with non-default blocks that uses common html tags like `h1`, `p`, `ul` and so forth breaks the design.

```html
<div class="prose">
    <!-- default WordPress blocks -->
    <p>Some default paragraph content goes here.</p>
    
    <!-- a custom block -->
    <div class="some-custom-block">
        <p>Here goes a custom paragraph for some poorly made up reason.</p>
    </div>
</div>
```

A way I've found to deal with this is to change the root CSS selector in `/src/index.js` on line `49` from `${className}` and `${className}-${modifier}` to `${className} >` and `${className}-${modifier} >`, changing the selector to only apply to direct child tags.

**Currently**

```js
    addComponents(
        all.map((modifier) => ({
          [modifier === 'DEFAULT' ? `.${className}` : `.${className}-${modifier}`]: configToCss(
            config[modifier]
          ),
        })),
        variants('typography')
      )
```

**My hard-coded solution only fitting for my specific case**

```js
    addComponents(
        all.map((modifier) => ({
          [modifier === 'DEFAULT' ? `.${className} >` : `.${className}-${modifier} >`]: configToCss(
            config[modifier]
          ),
        })),
        variants('wpTypography')
      )
```

Allowing to override the root CSS selectors with some function or a **more tailwind-y way** would be nice. 😊

Hope it makes sense.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

Would the `className` option work for you?

E.g.: https://play.tailwindcss.com/0u4BEuD6dW?file=config

**Comment by pierreminik** [comment]
Hey Robin. 😊

As far as I understand it, using `className` only works for non-modifiers since the component function maps the modifiers. Wouldn't the result then be: `.abc > .prose-${modifier} >` instead of `.abc-${modifier} > .prose `?

Applying the `prose` class to every default WordPress block is not possible without some quirky, hacky workaround, and I guess this goes for other block based CMS' too.

**Comment by hartwm** [comment]
Hi @pierreminik,
 
I am using tailwind in WordPress with custom blocks and running into this exact same issue. I don't have a good solution at the moment, but a few ideas to maybe point in the right direction for this to be solved.

I was playing with using :not selector however this doesn't work great because the editor doesn't wrap freeform styles so in order for this to work you would have to automatically wrap parts of the freeform in divs. It breaks the modifier as well. It would be easier just to wrap the Gutenberg freeform in a group with prose options. This is not the answer, but an example is here if it gives anyone else ideas -> https://play.tailwindcss.com/U5MCdi2nTa

Perhaps there is an option to apply prose at the @layer base and then have a `.reset` class that clears these styles out for all custom components of the theme. An inverse of .prose. It would be much easier to wrap my hardcoded header and footer and custom Gutenberg blocks in a single class.

**Comment by pierreminik** [comment]
Hi @hartwm ,

With how widespread WordPress is I definitely think there is benefits to be gained finding a resilient solution so Tailwind-based themes can enjoy the `.prose` typography for Gutenberg content.

I'm not sure I understand the `.page-wrapper` with `important` solution – wouldn't all elements in `.prose` still get the typography styling then?

The `:not` tactic and using `override-prose` is interesting. Would this require a hook into non-default widgets to apply this class?

I currently solve my issue with applying `prose` typography only to direct child elements. But I have only used my own custom blocks so I'm not sure how that solution would work with other blocks. Coming to think of it I also foresee issues with default blocks within an `<InnerBlock/>`.

**Comment by hartwm** [comment]
@pierreminik 

>I'm not sure I understand the .page-wrapper with important solution – wouldn't all elements in .prose still get the typography styling then?

An example is perhaps a better explaination. In my case I use a custom theme with custom blocks in conjunction with built-in core blocks (not 3rd parties).
https://play.tailwindcss.com/D823kV7Aiq

**Comment by adamwathan** [comment]
Hey! As of the latest release, you can use the `not-prose` class on non-default blocks to escape out of the prose styles:

```html
<div class="prose">
    <!-- default WordPress blocks -->
    <p>Some default paragraph content goes here.</p>
    
    <!-- a custom block -->
    <div class="not-prose some-custom-block">
        <p>Here goes a custom paragraph for some poorly made up reason.</p>
    </div>
</div>
```

Here's the documentation on that:

https://tailwindcss.com/docs/typography-plugin#undoing-typography-styles

Outside of what that does I'm afraid there's no really anything we can do here — even that solution was dependent on new features being added to CSS that are only seeing good enough browser support to use them.

Hope that helps!
