### ISSUE TITLE
Overrides kill all styling

### ISSUE THREAD

**Issue by selfagency** [tailwindlabs/tailwindcss-typography#145]
For some reason, if I do any sort of customization of this plugin's styles in my `tailwind.config.js`, it breaks everything.

Without any overrides in my Tailwind config:

![image](https://user-images.githubusercontent.com/2541728/108569006-263e0300-72d9-11eb-867b-155e7972f8a9.png)

After adding the following to my Tailwind config:

```javascript
      typography: {
        DEFAULT: {
          css: {
            color: '#222'
          }
        }
      }
```

![image](https://user-images.githubusercontent.com/2541728/108569058-3fdf4a80-72d9-11eb-9600-90e016278caa.png)

Any ideas how to resolve this? Thanks.

**Comment by chasegiunta** [comment]
@selfagency did you place your rules in the `extend` key? Should be:
```
extend: {
  typography: {
        DEFAULT: {
          css: {
            color: '#222'
          }
        }
      }
}
```

**Comment by elisealcala** [comment]
I have the same problem and I'm using the example from the docs.

Before: 
![image](https://user-images.githubusercontent.com/16949569/109178870-4ea18380-7757-11eb-810e-dd00322d913c.png)


After changing the tailwind config.

![image](https://user-images.githubusercontent.com/16949569/109179123-932d1f00-7757-11eb-91b0-46e1d3bdc07c.png)

**Comment by chasegiunta** [comment]
@elisealcala Can you recreate on https://play.tailwindcss.com/ ?

**Comment by selfagency** [comment]
@chasegiunta It was indeed placed under the `extend` key

**Comment by elisealcala** [comment]
@chasegiunta I was able to recreate it with version v1.9.6

**Comment by chasegiunta** [comment]
@elisealcala Ah gotcha. Which version of the tailwind typography plugin are you using?

>As of v0.3.0, @tailwindcss/typography is designed for Tailwind CSS v2.0+.

**Comment by selfagency** [comment]
Here's [my reproduction](https://play.tailwindcss.com/1XGQiJedQs?file=config), also in 1.9.6. I am using typography "^0.4.0".

**Comment by selfagency** [comment]
Side note — shouldn't using `"tailwindcss": "npm:@tailwindcss/postcss7-compat",` in my dependencies give me the latest version of Tailwind, not 1.9.6?

**Comment by chasegiunta** [comment]
@selfagency Probably. Not sure what's going on there.

Looks like not using Tailwind 2.0+ is the issue for both of y'all. If you cannot upgrade to Tailwind 2.0, I would drop down to tailwindcss-typography 2.0 and that should resolve your issues. Make sure you read the past configuration in the readme as the configuration structure changed from 2.0 to 3.0

**Comment by selfagency** [comment]
Ok, I figured out my issue. Nuxt 2.15 no longer requires the compatibility package.

**Comment by chasegiunta** [comment]
@selfagency good to close the issue?
