### ISSUE TITLE
Support for dl, dt and dd tags

### ISSUE THREAD

**Issue by apoorvmote** [tailwindlabs/tailwindcss-typography#146]
I not only use `dl`, `dt` and `dd` tags but I nest them inside of each other. E.g. `dd` has another `dl` inside of it.

I have to add tailwind classes manually to make `dt` semi bold and add left padding to `dd`.

Also I am terrible designer so I would like some great designer to take a look once over.

**Comment by Svish** [comment]
I tend to get data using definition lists too, and would be awesome if this typography plugin could give those some great looking styles as well. Because I suck at this 😛

**Comment by adamwathan** [comment]
Hey! Can you provide an example of how this might look in the type of content this plugin is meant to style? Not opposed to working on this at some point but don't have a clear picture in my mind of the exact scenario. Thanks!

**Comment by Svish** [comment]
Currently working on a bible study website where `<dl>` is sometimes used within studies for lists of concepts/terms with descriptions/explanations. Below are links to three cases of that, and a screenshot of one of them. Working on rewriting this website with Next.js and Tailwind, but that version is not live yet. Note that the lists are all within their lesson/study, part of the text content that will be styled by the `prose` plugin, not something separate that comes after the text.

* https://bibelstudiet.no/2019/3/12#2
* https://bibelstudiet.no/2019/3/10#5
* https://bibelstudiet.no/2021/1/8#4

![image](https://user-images.githubusercontent.com/142162/133002881-9c43720f-ee86-4348-842d-9c8b7f9cc2fb.png)

More general usage of the `<dl>` tag, perhaps more common, is glossaries of terms or keywords.

Definition lists can have both multiple terms and multiple definitions for each "block". So you can have two or more terms followed by one definition, one term followed by two or more definitions, and multiple of both as well. Regarding styling it should probably also be taken into account that a definition could have multiple paragraphs as well.

I tend to style definition lists like shown in the screenshot, as tiny headers (same typography as other text, just bolder), with the definitions indented. In my local Tailwind version, I've played around with using a dot in front of the definitions, basically same as this plugin uses for unordered lists, but not sure if I like it or not. 🤷‍♂️ Leaning towards maybe not, but not sure. Don't really know what I'm doing when it comes to typography, hence why I wish this was part of the prose plugin so I didn't have to think about it 😛

![image](https://user-images.githubusercontent.com/142162/133003105-15cbb021-b0b1-4541-a7ed-de888efed19e.png)

Hope this helps. 🙃

**Comment by jlcara** [comment]
@adamwathan this could be also applied to a **FAQ section**.

I think that be the best approach could be by applying a way to "**clone**" an element style via `tailwind.config.js`.
_By the way, is that already possible?_

In my case, I'd like `dt` tag to have the same styles as `h3` tag.

![CleanShot 2021-11-23 at 08 40 52@2x](https://user-images.githubusercontent.com/18506703/142986533-f2abd94f-89d6-41b3-a534-c1da3d3ba6b9.png)

**Comment by sebastienbarre** [comment]
The plugin demo actually has a section that could be a good target for definition lists:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/329967/157305409-63b3d31c-3f07-4cca-91a1-64b7fd7adc8a.png">

I'm saying that mostly because I'm coming from Markdown, where there is no easy way to reproduce what is shown here, but Markdown does support definition list that could be rendered like the above ultimately.
```
Term with *inline markup*

: Definition **1**
```

**Comment by caendesilva** [comment]
I'm always so surprised this is still not a thing. I personally don't actually know how Tailwind works under the hood, but I feel like it should be pretty simple to add some simple styling?

### Here's my suggestion for a basic style made to match browser defaults
![localhost_8080_test_2021-12-30-160234 html (1)](https://user-images.githubusercontent.com/95144705/209643135-d7e3f2d2-9663-423f-b243-4e52fed5ef75.png)

**This is literally just two styles.** `font-bold` for `<dt>` elements and `ml-4` for `<dd>`.
It makes a world of difference in my opinion.

**Comment by ChildishhAlbino** [comment]
I like @caendesilva's suggestion - this would be a really useful feature to have included.

**Comment by reinink** [comment]
Hey! Thanks for this suggestion — I've just added styles for description lists in #316. We're hoping to get a new release out really soon, but until then you can use our insiders release:

```sh
npm install @tailwindcss/typography@insiders
```
