### ISSUE TITLE
Customizing colors by extending the palette with a specified hex code breaks prose-color

### ISSUE THREAD

**Issue by jpvalery** [tailwindlabs/tailwindcss-typography#150]
Hi there,

I've extended my palette following the [instructions of the documentation](https://tailwindcss.com/docs/customizing-colors#extending-the-defaults). 

However, by doing so, it breaks the `prose-color` class. Whether it's with a custom color (`prose-custom`) or base color (`prose-blue`), the class doesn't apply and the link remains dark. 

This currently breaks all `prose-color` options. I can't even use `prose-blue` for instance.

## How to repro (100%): 

With the following tailwind.config.js file, the prose-color doesn't work: 

```javascript
const colors = require('tailwindcss/colors')

module.exports = {
  purge: ['./pages/**/*.js', './components/**/*.js', './elements/**/*.js'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        custom: '#CB3232',
        cta: colors.blue,
      },
      margin: {
        '-menu': '-28rem',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/typography')],
}
```

Test page
```javascript
export default function Test() {
  return (
    <div className="mx-auto py-24 grid grid-flow-row justify-items-center bg-white">
      <div className="prose prose-xl prose-custom text-center py-8">
        <p>
          Lorem ipsum sit dolor
          <a href="#">amet</a>
        </p>
      </div>
      <div className="prose prose-xl prose-blue text-center py-8">
        <p>
          Lorem ipsum sit dolor
          <a href="#">amet</a>
        </p>
      </div>
    </div>
  );
}
```

Result: 
<img width="696" alt="image" src="https://user-images.githubusercontent.com/4112343/109531780-52e6dd00-7a86-11eb-98af-f614fe0be6f7.png">

However, when we edit the color customization based on a hex code: 

```javascript
const colors = require('tailwindcss/colors')

module.exports = {
  purge: ['./pages/**/*.js', './components/**/*.js', './elements/**/*.js'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        custom: colors.red,
        cta: colors.blue,
      },
      margin: {
        '-menu': '-28rem',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/typography')],
}
```
Then it works: 
<img width="723" alt="image" src="https://user-images.githubusercontent.com/4112343/109531944-8c1f4d00-7a86-11eb-8c51-bb6821049710.png">

I hope this helps! Unfortunately, I have 0 clue on how to fix this :( I don't know if it's on my end and I messed up somewhere or if it's on TailwindCSS' end. 

Let me know if there's anything else I can do to help

**Comment by LostKobrakai** [comment]
`colors.red` is an object with all the red shades in tailwind – not just a single color. You'd likely need to set all the shades the plugin uses for your custom color. Currently that seems to be only the `600` one: https://github.com/tailwindlabs/tailwindcss-typography#color-modifiers

So this should make it work:
```
 colors: {
    custom: { 600: '#CB3232' }
 }
```

**Comment by jpvalery** [comment]
Thanks for the suggestion! It _partially_ works. 

If there's a custom color defined only by the hex code, then it doesn't work:

```javascript
const colors = require('tailwindcss/colors')

module.exports = {
  purge: ['./pages/**/*.js', './components/**/*.js', './elements/**/*.js'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        custom: { 600: '#CB3232' },
        other: '#A56D5E',
        cta: colors.blue,
      },
      margin: {
        '-menu': '-28rem',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/typography')],
}
```

<img width="495" alt="image" src="https://user-images.githubusercontent.com/4112343/109815992-3cfc2800-7bfe-11eb-9087-d29dd95c64e0.png">

However, removing the hex code color makes it work: 

```javascript
const colors = require('tailwindcss/colors')

module.exports = {
  purge: ['./pages/**/*.js', './components/**/*.js', './elements/**/*.js'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        custom: { 600: '#CB3232' },
        cta: colors.blue,
      },
      margin: {
        '-menu': '-28rem',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/typography')],
}
```

<img width="380" alt="image" src="https://user-images.githubusercontent.com/4112343/109816096-59986000-7bfe-11eb-92ef-d40fda67e6cf.png">

While this can be a short term fix (or see below for my workaround for now), it doesn't address the underlying issue that a single custom color will break all of the prose-color options. :( 

------------------------------

(In the mean time, I found a workaround with custom link colors for prose in `tailwind.config.js`)
```javascript
      typography: {
        DEFAULT: {
          css: {
            a: {
              color: '#FFFFFF',
              '&:hover': {
                color: '#D8D8C7',
              },
            },
          },
        },
      },
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Are you on the latest version? We check wether the color can be used or not here: https://github.com/tailwindlabs/tailwindcss-typography/blob/bfb5f97cda53cb087ae324d5d193e6d3fec01e52/src/styles.js#L1100

That said, you also require a value `600` for each color you want to use, hope this helps!
