### ISSUE TITLE
Firefox padding right when pre code blocks has horizontal scroll

### ISSUE THREAD

**Issue by krompaco** [tailwindlabs/tailwindcss-typography#154]
### What version of @tailwindcss/typography are you using?

0.3.1

### What version of Node.js are you using?

v14.15.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### Reproduction repository

https://krompaco.nu/2021/02/please-do-this-with-your-swagger-enabled-web-apis/

Look at the first code sample in reproduction link in Firefox. When horizontal scrollbar appears there is no padding-right on the dark area. Chrome displays it nicely.

![firefox-pre-code](https://user-images.githubusercontent.com/12028930/112118600-d2b32380-8bbc-11eb-9f4c-9e812fdfbdfa.png)

You have this issue too in your documentation, make a smaller viewport here and look for example here: https://tailwindcss.com/docs/adding-base-styles

**Comment by krompaco** [comment]
I have now filed a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1741798

Think you can go there and vote on it!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

As you mentioned yourself this seems like a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=372498

Going to close this since I don't think we can do much about it here and hopefully the bug gets resolved soon.

---

Always having a `code` inside `pre` sort of depends on the library you use to parse your markdown, but if that works for you then totally go ahead!

**Comment by krompaco** [comment]
There is a sample of a very lightweight "prose" alternative and also code samples in this post where you can see the solution I refer to in play: https://krompaco.nu/2022/08/hosting-this-blog-on-azure-and-switching-setup/

**Comment by stefanprobst** [comment]
so the trick is to set `display: inline-table; padding-right: 1em;` on `code`?

**Comment by krompaco** [comment]
@stefanprobst That solves it if you are outside of a Typography element. It seems a bit tricky to solve by extending the plugin but slightly easier to edit it. See the commit I linked above.
