### ISSUE TITLE
Dark theme not compatible with prose / typography using new JIT engine

### ISSUE THREAD

**Issue by DoctorDerek** [tailwindlabs/tailwindcss-typography#157]
### What version of @tailwindcss/typography are you using?

v0.4.0

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/DoctorDerek/steven-terner.github.io/blob/master/pages/demo.js

---------

Hi, I'm crossposting this from tailwindlabs/tailwindcss-jit#191 because it affects both libraries.

---------

Following up on a comment from @danjac about PR #153 -- there's a bug that I'm reporting to jit & typography.

Here's an example repo that uses dark theme with prose / Tailwind typography: https://github.com/timlrx/tailwind-nextjs-starter-blog/ (not jit) and it's live here: https://tailwind-nextjs-starter-blog.vercel.app/

As you can see, prose works fine with dark mode in the old system (except for the caveat about responsive classes addressed by that PR, #153):
![image](https://user-images.githubusercontent.com/761231/113065869-2c988800-917f-11eb-8b62-1ea72a94f10e.png)

However when I tried that in a derivative from that template using the new jit engine, prose doesn't work with dark mode.
![image](https://user-images.githubusercontent.com/761231/113065897-3c17d100-917f-11eb-893b-041222fdc577.png)

Source code: https://github.com/DoctorDerek/steven-terner.github.io/blob/master/pages/demo.js Live version: http://steven-terner-github-io.vercel.app/demo (That page won't stay up for particularly long, but I didn't want to spin up a new project just for this issue, sorry.)

```
 <article className="mx-auto space-y-6 prose">
        <SectionContainer>
          <p>
            My portfolio showcases 
```

I'm happy to look into it more myself if you'd like to assign me to following up on it, but now I'm just the messenger 😀

**Comment by DoctorDerek** [comment]
I'm not sure if this is implementation-dependent or was fixed in a recent version change, but prose seems to work correctly with dark mode now. See https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/14 live at https://tailwind-nextjs-starter-blog-git-upgrade-timlrx.vercel.app/

Happy to re-open if it's a lingering issue.

**Comment by danjac** [comment]
@DoctorDerek thanks for looking into this.
