### ISSUE TITLE
The bug report form doesn't have a field to describe the issue

### ISSUE THREAD

**Issue by simonacca** [tailwindlabs/tailwindcss-typography#163]
### What version of @tailwindcss/typography are you using?

irrelevant

### What version of Node.js are you using?

irrelevant

### What browser are you using?

irrelevant

### What operating system are you using?

irrelevant

### Reproduction repository

https://www.youtube.com/watch?v=VtvjbmoDx-I

**Comment by simonacca** [comment]
As per the title, the form to open a bug doesn't have a field to actually describe the issue
![image](https://user-images.githubusercontent.com/1206381/114105102-69c1f000-98cc-11eb-9ff4-63134ea04ea3.png)

**Comment by adamwathan** [comment]
Should be fixed now, thanks!
