### ISSUE TITLE
[Bug] : Responsive variants and max-w-full confusion

### ISSUE THREAD

**Issue by phil-scott-78** [tailwindlabs/tailwindcss-typography#168]
### What version of @tailwindcss/typography are you using?

v0.4.0

### What version of Node.js are you using?

v14

### What browser are you using?

n/a

### What operating system are you using?

windows / ubuntu

### Reproduction repository

https://play.tailwindcss.com/WfM4NeooIp

### Describe your issue

I've got some `prose` content that I want to make responsive that's in a flex container. So, it looks like this `prose prose-sm lg:prose-lg xl:prose-xl max-w-full`

Feels like I went down the wrong path because my solution is pretty convoluted, but I'm at a loss to how I could have done it better.

1. `max-w-full`'s width is overriden by `lg:prose-lg` and `xl:prose-xl`. To get this to work you end up with `prose prose-sm lg:prose-lg lg:max-w-full xl:prose-xl xl:max-w-full max-w-full`
2. If I have `prose-lg` for large and `prose-xl` for extra-large you probably can guess what I wanted for medium size screens. This took a minute to figure out, but now my selector looks like this: `prose prose-sm md:prose md:max-w-full lg:prose-lg lg:max-w-full xl:prose-xl xl:max-w-full max-w-full` and might be what bug #67 was trying to get at.
3. I'm not 100% sure, but because we are setting max-width (and even though I'm saying ignore that) I need to now set `max-w-0` on my flex container to get it to behave properly with overflow items.

It almost feels like the width should be extracted away from the default and placed in their own selector named like `prose-max-w-sm` , `prose-max-w-md`, etc. 

Tried to get a simple repo up here - https://play.tailwindcss.com/WfM4NeooIp

**Comment by MartinMa** [comment]
@phil-scott-78 If I were you, I'd remove the `max-width` property from the `prose` default config and then add `max-width` with an extra class when needed, like you suggested.

This is how you need to extend your config.

```js
// config example
theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            maxWidth: null,
          },
        },
      },
    },
  },
```

I also fixed your example here: https://play.tailwindcss.com/xQn2Sa2TiR?file=config

**Comment by phil-scott-78** [comment]
I came on here suggesting the default config remove the max-width and it didn't even occur to me to do so myself in my config! That's great.

I'd still propose this be the default due to the awkwardness in removing it via the utility classes, but until then I'm updating my config. 

Thanks again for the snippet!

**Comment by simonswiss** [comment]
Hey!

Sorry about the lack of responsiveness here. This should not be an issue anymore with the v0.5 of the plugin, since the prose selectors are now "flat" and you can therefore override those with utility classes without getting into specificity issues.

For example, the `max-w-full` in your example would actually end up winning and not being overridden.

I'll close this issue for now 👍

**Comment by phil-scott-78** [comment]
Oh great, I'll revisit my config and get it lined up better with how things are configured in the latest release
