### ISSUE TITLE
[Bug] : <strong> tags within headings makes text lighter in weight...

### ISSUE THREAD

**Issue by ewhicher** [tailwindlabs/tailwindcss-typography#170]
### What version of @tailwindcss/typography are you using?

0.3.1

### What version of Node.js are you using?

16.0.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://tailwindcss-typography.netlify.app/

### Describe your issue

Adding a `<strong>` tag within any `<h>` tag is the same or slightly lighter in weight (600) than the default heading styles (800, 700, 600).

I know these can be customised but I just wondered if this was something that should work out of the box.

Thanks!

**Comment by simonswiss** [comment]
I'd consider having a `strong` tag inside a heading somewhat of an "edge case".

I know you may not be able to control the HTML coming in (one of the main reasons for this plugin to exist), but the real fix would be questioning upstream: why use a `strong` tag inside a heading?

The semantic meaning of a heading tag gives it hierarchical importance in the document. Adding a `strong` tag doesn't really add any "value/meaning". I can only assume it's done for styling reasons?

I don't think it has any negative impact, but it likely doesn't make the HTML code any better or more semantic, so I don't think default styles should be catering for this scenario? I'd probably customise the plugin styles for this.

**Comment by adamwathan** [comment]
Hey thanks for reporting, agree this is not good default behavior and easy to improve so I've made it better here: https://github.com/tailwindlabs/tailwindcss-typography/pull/180
