### ISSUE TITLE
prose prose-sm sm:prose

### ISSUE THREAD

**Issue by davidmles** [tailwindlabs/tailwindcss-typography#187]
### What version of @tailwindcss/typography are you using?

Latest

### What version of Node.js are you using?

Tailwind Play

### What browser are you using?

N/A

### What operating system are you using?

N/A

### Reproduction repository

https://play.tailwindcss.com/vtPzGvl6zS

### Describe your issue

When using `prose prose-sm sm:prose`, other classes don't work properly when reaching the SM breakpoint.

Please visit https://play.tailwindcss.com/vtPzGvl6zS

You will see a very small example where I added the `prose-blue` class. The link is blue in the smallest size, but as soon as you reach the SM breakpoint (or higher), the `prose-blue` class doesn't take any effect anymore.

Is this a bug?

**Comment by MattAppleton** [comment]
Same kind of issues here...

**Comment by Maybach91** [comment]
Got the same issue. Then i asked myself why should i need `sm:prose`? (thats why it doesn’t work) After removing `sm:prose` my theme overwrites just worked.

**Comment by davidmles** [comment]
> Got the same issue. Then i asked myself why should i need `sm:prose`? (thats why it doesn’t work) After removing `sm:prose` my theme overwrites just worked.

If you don't set `sm:prose` in my example, you will stay with the `prose-sm` size for all screen sizes.

**Comment by bradleybensmith** [comment]
This worked for me:

`prose prose-sm prose-blue md:prose md:prose-blue`

**Comment by davidmles** [comment]
> This worked for me:
> 
> `prose prose-sm prose-blue md:prose md:prose-blue`

Thanks. So, it you want to keep the effect, you have to set `prose-blue` again for the sm modifier.
