### ISSUE TITLE
Prose works in responsive mode, but not when browser reports a mobile agent string at same size

### ISSUE THREAD

**Issue by rrrodzilla** [tailwindlabs/tailwindcss-typography#188]
### What version of @tailwindcss/typography are you using?

^v0.4.1

### What version of Node.js are you using?

v15.10.0

### What browser are you using?

Firefox

### What operating system are you using?

Arch Linux (manjaro)

### Reproduction repository

https://github.com/rrrodzilla/tailwindcss-typography-plugin-issue-repro

### Describe your issue

I'm using [Zola site generator](https://www.getzola.org) to create my static site using markdown files.  The markdown renders fine when the browser is resized responsively, but not if it reports a UA of a mobile device even if the screen is the same size.  The font doesn't resize and appears tiny on a mobile device.  Pictures for clarity and the repro demos the issue:
![responsive_typography](https://user-images.githubusercontent.com/24578097/128441039-41517284-0e2f-451c-b958-adff194bb7c3.png)
And now on a mobile device:
![mobile_typography](https://user-images.githubusercontent.com/24578097/128441090-ef3a8708-ffeb-44c9-888c-56ce4627d39d.png)

**Comment by adamwathan** [comment]
Hey! My hunch is that it's because you're missing the `<meta>` tag needed for responsive design stuff:

```
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
```

This isn't unique to Tailwind, this is just kinda standard developing-for-mobile stuff 👍🏻  Can read more about it here:

https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag

**Comment by rrrodzilla** [comment]
Ugh...so basic.  That did it.  Thanks Adam.  Hope fatherhood is treating you well.  Congrats and thanks again!
