### ISSUE TITLE
Upper Roman list style text is overlapping

### ISSUE THREAD

**Issue by rockmandash** [tailwindlabs/tailwindcss-typography#195]
### What version of @tailwindcss/typography are you using?

v0.4.1

### What version of Node.js are you using?

v12.0.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/6W0CGdn1o7

### Describe your issue

Please see this screenshot and Tailwind Play https://play.tailwindcss.com/6W0CGdn1o7

![image](https://user-images.githubusercontent.com/7580792/131992633-ee067f6c-ebb4-4c79-b2b8-4d920f10ad61.png)

The text is overlapping

**Comment by adamwathan** [comment]
Hey! Unfortunately I don't think we can do much about this without other negative side-effects — if we increase the amount of padding there by default it will look worse for non-Roman formats which doesn't feel like the right trade-off.

If you need to use this list style I would recommend making your own customizations to accommodate it by adding some additional padding:

https://github.com/tailwindlabs/tailwindcss-typography#customization

Hope that helps, sorry it's not exactly what you need out of the box.
