### ISSUE TITLE
Parsing media queries in custom css for '.lead' is overwritten

### ISSUE THREAD

**Issue by jacobthesheep** [tailwindlabs/tailwindcss-typography#211]
### What version of @tailwindcss/typography are you using?

v0.5.0-alpha.3

### What version of Node.js are you using?

v14.17.1

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/jacobthesheep/jacoblamb.me

### Describe your issue

After updating to TailwindCSS v3.0.0-alpha.2 & @tailwindcss/typography to v0.5.0-alpha.3, parsing dark-mode media queries in custom css for the '.lead' class is overwritten by the non dark mode css.

<img width="460" alt="Screen Shot 2021-11-08 at 12 05 20" src="https://user-images.githubusercontent.com/44789941/140810439-e11cf8c3-0deb-4b81-9d67-f21d6c391353.png">

**Comment by adamwathan** [comment]
Hey! Can you please create a minimal reproduction using Tailwind Play? Will be a lot easier to dig into and really understand what you are talking about vs. going through the whole codebase for your personal site 👍🏻 Thanks!

**Comment by jacobthesheep** [comment]
@adamwathan Sorry forgot to close this issue, it's been fixed.

**Comment by adamwathan** [comment]
Best news ever 😄 Thanks!
