### ISSUE TITLE
Generated prose styles are not being purged.

### ISSUE THREAD

**Issue by jjaimealeman** [tailwindlabs/tailwindcss-typography#215]
### What version of @tailwindcss/typography are you using?

"@tailwindcss/typography": "^0.4.1"

### What version of Node.js are you using?

node -v v17.0.1

### What browser are you using?

Firefox Developer Edition 94.0b9 (64-bit) & Chromium Version 95.0.4638.54

### What operating system are you using?

Pop OS Linux 21.04

### Reproduction repository

https://github.com/jjaimealeman/my-static-boilerplate

### Describe your issue

JIT enabled. Purge is working without issue.

Installed `@tailwindcss/typography` and used the `prose` class on exactly one paragraph - as a test. Copy/Paste below.
```
<p class="prose"><a href="#">Lorem ipsum dolor</a> <strong>sit amet consectetur</strong> <em>adipisicing elit</em>. Voluptates blanditiis illum accusamus quod! Eum nulla corrupti fuga ipsa ducimus magnam voluptatem asperiores ex dolores, ad ut quaerat! <a href="#">Obcaecati nobis</a> sed ea quibusdam, dolorum quas numquam possimus provident saepe similique earum facere corrupti sequi repudiandae repellat suscipit quam atque natus explicabo! Odit illum fugiat consequatur iusto.</p>
```
This paragraph contains one element of each `<a>`, `<strong>`, `<em>`. 
So I did expect to see in my output CSS `.prose a`, `.prose strong`, `.prose em`. However `.prose em` does not exist. Not a big problem, it's just _italics_.

BUT!

The following styles were not purged.
`.prose a, .prose a:focus, .prose a:hover, .prose, .prose [class~="lead"], .prose a, .prose strong, .prose ol[type="A"], .prose ol[type="a"], .prose ol[type="A s"], .prose ol[type="a s"], .prose ol[type="I"], .prose ol[type="i"], .prose ol[type="I s"], .prose ol[type="i s"], .prose ol[type="1"], .prose ol > li, .prose ul > li, .prose ol > li:before, .prose ul > li:before, .prose hr, .prose blockquote, .prose blockquote p:first-of-type:before, .prose blockquote p:last-of-type:after, .prose h1, .prose h2, .prose h3, .prose h4, .prose figure figcaption, .prose code, .prose code:after, .prose code:before, .prose a code, .prose code, .prose h1, .prose h2, .prose h3, .prose h4, .prose thead, .prose pre, .prose table, .prose pre, .prose pre code, .prose pre code:after, .prose pre code:before, .prose table, .prose thead, .prose thead th, .prose tbody tr, .prose tbody tr:last-child, .prose tbody td, .prose ol, .prose p, .prose ul, .prose figure, .prose img, .prose video, .prose figure > *, .prose h2 code, .prose h3 code, .prose li, .prose ol ol, .prose ol ul, .prose ul ol, .prose ul ul, .prose > ul > li p, .prose > ul > li > :first-child, .prose > ul > li > :last-child, .prose > ol > li > :first-child, .prose > ol > li > :last-child, .prose h2 + *, .prose h3 + *, .prose h4 + *, .prose hr + *, .prose tbody td:first-child, .prose thead th:first-child, .prose tbody td:last-child, .prose thead th:last-child, .prose > :first-child, .prose > :last-child`

The full unedited classes are linked below, starting with line#329 in my CSS.

https://github.com/jjaimealeman/my-static-boilerplate/blob/e94ae5f5e57ecb34fe8c42955fbf2b6f00372f62/build/assets/css/global.css#L329

Is this the intended behavior?

Should I not worry?

Why isn't it being purged?

Thank you for developing a fine plugin. Aside from the above issue, it works beautifully :+1:

**Comment by jjaimealeman** [comment]
Awaiting a response from Devs.

**Comment by scratchmex** [comment]
See #61
