### ISSUE TITLE
`prose` being purged in compiled css | SvelteKit

### ISSUE THREAD

**Issue by lamaqdahodwala** [tailwindlabs/tailwindcss-typography#218]
### What version of @tailwindcss/typography are you using?

v0.4.1

### What version of Node.js are you using?

v16.9.1

### What browser are you using?

Microsoft Edge

### What operating system are you using?

Windows (WSL)

### Reproduction repository

https://github.com/lamaqdahodwala/bug/

### Describe your issue

I am trying to use this module to render markdown on my app. However, when I apply the `prose` class to a div that surrounds my content, there are no styles being applied. Doing further investigation, I was not able to find any `.prose` classes on the CSS rendered on the site. Is there a reason why Tailwind is purging it? Or is it another problem?

**Comment by adamwathan** [comment]
The problem is you are missing `@tailwind components` in your CSS:

```diff
  <!-- __layout.svelte -->
  <slot></slot>
  
  <style global lang='postcss'>
      @tailwind base;
+     @tailwind components;
      @tailwind utilities;
  </style>
```

The typography styles are injected into the components layer and you were not including that layer in your stylesheet.

**Comment by lamaqdahodwala** [comment]
I see. Thanks for the info!

**Comment by diemah77** [comment]
> The problem is you are missing `@tailwind components` in your CSS:
> 
> ```diff
>   
>   <slot></slot>
>   
>   <style global lang='postcss'>
>       @tailwind base;
> +     @tailwind components;
>       @tailwind utilities;
>   </style>
> ```
> 
> The typography styles are injected into the components layer and you were not including that layer in your stylesheet.

I guess this should be added to the docs as I ran into the same issue and didn't know why prose classes where not generated.
