### ISSUE TITLE
"@apply prose" breaks all further instances of @apply

### ISSUE THREAD

**Issue by Joobs** [tailwindlabs/tailwindcss-typography#219]
### What version of @tailwindcss/typography are you using?

3.0.0-alpha.2

### What version of Node.js are you using?

v14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/cM8QtjobVQ

### Describe your issue

I was experimenting with the new Tailwind JIT CDN and I noticed an issue with the Typography plugin. I've not tried it on a production setup.

If i use `@apply prose` the compiler seems to ignore any future `@apply` rules (either on the same line, or further down the CSS).
The bug is present in Tailwind V3 Alpha2, but compiles as expected if i switch to V2.2.19. Switch between the two versions to see the differences. In my example it ignores the `prose-2xl` and `@apply text-red-500` rules after `prose` is applied.

**Example:** (switch between Tailwind versions)
https://play.tailwindcss.com/ogV2iFjxm3

**Tailwind 3 Alpha:**
<img width="552" alt="Screenshot 2021-11-29 at 06 12 45" src="https://user-images.githubusercontent.com/458935/143812498-c46e8882-0885-4223-880d-b23f5dfc079d.png">

**Tailwind 2:**
<img width="725" alt="Screenshot 2021-11-29 at 06 13 09" src="https://user-images.githubusercontent.com/458935/143812543-102fc495-6793-48c0-a581-c2a354390134.png">

**Comment by LiamThursfield** [comment]
Unsure if this is related but I have this:

```
.mce-content-body {
    @apply prose;
}
```

Looking through the generated CSS I have found the broken bit off CSS is:
```
.mce-content-body :where(ul ul{
    margin-top: 0.75em;
    margin-bottom: 0.75em;

}
```

So any CSS generated after this doesn't work/is ignored.

**Comment by thecrypticace** [comment]
Thanks for the report. I just checked and this appears to work fine in the latest version of Tailwind CSS v3!
