### ISSUE TITLE
prose-[custom color] doesn't work with TailwindCSS 3.0 anymore

### ISSUE THREAD

**Issue by jpvalery** [tailwindlabs/tailwindcss-typography#222]
### What version of @tailwindcss/typography are you using?

0.5.0

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/jpvalery/advisorship-consultancy

### Describe your issue

Hi there!

Hope you're alright.

I was working on updating to TailwindCSS 3.0 and noticed that `prose` wasn't working with my custom colors anymore.

In my `tailwind.config.js`:
```
  theme: {
    extend: {
      colors: {
        advisor: colors.emerald,
        consultant: colors.violet,
        cta: colors.blue,
      },
    },
```
and now `prose-advisor` doesn't display the right color anymore:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/4112343/145486293-de09ce77-fc8d-4e69-8dd7-074fcf97b700.png">

See it in the wild [here](https://growthmontreal.com/advisorship)

Happy to answer any questions you might have!

**Comment by marcreichel** [comment]
Same here. The "default" colors (`prose-red`, `prose-yellow`, `prose-green`, `prose-blue`, `prose-indigo`, `prose-purple`, `prose-pink`) are not working as well.

**Comment by marcreichel** [comment]
So apparently the new "syntax" now seems to be `prose prose-a:text-[color]-[shade]` in v0.5 according to the newest YouTube video of tailwindlabs https://youtu.be/GEYkwfYytAM?t=236 and the now updated/outsourced docs in 684cfc6f47ea7a24eedcf19b91f96fb56e84ddc6. So the docs just seemed to be outdated at the time of opening this issue...

**Comment by jpvalery** [comment]
That did the trick—good catch and thank you very much @marcreichel
