### ISSUE TITLE
is not good for darkMode

### ISSUE THREAD

**Issue by little3201** [tailwindlabs/tailwindcss-typography#225]
### What version of @tailwindcss/typography are you using?

0.5.0

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Edge, Safari 

### What operating system are you using?

windows11, macOS

### Reproduction repository

https://github.com/little3201/leafage-pw

### Describe your issue

when change to dark mode, some block disply like:
![image](https://user-images.githubusercontent.com/34156125/145913698-69d3aa30-0576-46e4-acec-88731c038690.png)

can not know what it is

**Comment by adamwathan** [comment]
Hey! Use the `prose-invert` class when in dark mode:

```html
<article class="prose dark:prose-invert">
  <!-- ... -->
</article>
```

This is new for v0.5.0/Tailwind 3, updating docs to include this as we speak 👍🏻

**Comment by mohammadazeemwani** [comment]
@adamwathan Do I always have to write this whole line ? `prose dark:prose-invert`
