### ISSUE TITLE
How to target nested elements with Tailwind Typography?

### ISSUE THREAD

**Issue by spences10** [tailwindlabs/tailwindcss-typography#227]
### What version of @tailwindcss/typography are you using?

latest

### What version of Node.js are you using?

14

### What browser are you using?

edge

### What operating system are you using?

wsl

### Reproduction repository

cheatsheets.xyz, https://github.com/spences10/cheat-sheets

### Describe your issue

Here's the discussion I started but realise it wasn't for Tailwind Typography

Possibly a bug as I've seen it when using the Typography plugin elsewhere

https://github.com/tailwindlabs/tailwindcss/discussions/6523

**Comment by spences10** [comment]
Oh! Looks like it's a DaisyUI bug!

With DaisyUI: https://play.tailwindcss.com/iWp6pl2vD6?file=config

Without DaisyUI: https://play.tailwindcss.com/4gM0NQjxxT?file=config

@saadeghi tagging you on this to possibly move it to DaisyUI

**Comment by saadeghi** [comment]
Thanks! created [an issue](https://github.com/saadeghi/daisyui/issues/337) for that
