### ISSUE TITLE
does not work `fontSize: theme('fontSize.2xl')` in tailwind.config.js

### ISSUE THREAD

**Issue by Code-Hex** [tailwindlabs/tailwindcss-typography#230]
### What version of @tailwindcss/typography are you using?

v0.5.0

### What version of Node.js are you using?

v16.8.0

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/Code-Hex/tailwindcss-typography-fontsize-bug

### Describe your issue

This is no longer reflected when upgrading from v0.4.1 to v0.5.0.
This is how it is set up
https://github.com/Code-Hex/tailwindcss-typography-fontsize-bug/blob/64798d103df4ac0048b1884b855b9cceb02774e7/tailwind.config.js#L10-L17

It doesn't seem to be reflected when an array is passed in like this

```js
fontSize: '1.875rem', // works fine!
fontSize: [ '1.875rem', { lineHeight: '2.25rem' } ] // does not work
```

**Comment by michtio** [comment]
Hijacking on this, it also doesn't work with:

tw config:

```
fontFamily: {
                primary: [
                    'Roboto',
                    'Helvetica',
                    'Arial',
                    'sans-serif'
                ],
 },
 ```
 
 typography config in TW:
 
```
css: {
   fontFamily: theme('fontFamily.primary'),
}
```

This generates the following ( broken ) CSS:

```
.prose{
    :where(font-family):not(:where([class~="not-prose"] *)): Roboto;
    :where(font-family):not(:where([class~="not-prose"] *)): Helvetica;
    :where(font-family):not(:where([class~="not-prose"] *)): Arial;
    :where(font-family):not(:where([class~="not-prose"] *)): sans-serif;
}
```

**Comment by slackday** [comment]
@michtio change

```
css: {
   fontFamily: theme('fontFamily.primary'),
}
```

to 

```
css: {
   fontFamily: theme('fontFamily.primary').join(', '),
}
```

**Comment by bradlc** [comment]
Hey @Code-Hex. The `theme` function returns the raw value from the theme, and the default `fontSize` values are arrays that you can't use directly in CSS. You need to use `theme('fontSize.3xl')[0]` to access just the font size for the `3xl` size. I opened a [PR](https://github.com/Code-Hex/tailwindcss-typography-fontsize-bug/pull/1) on your repo that shows how you can apply the font-size _and_ the line-height. I hope that helps!
