### ISSUE TITLE
[Nuxt.js] Improper descendant selectors

### ISSUE THREAD

**Issue by gomorizsolt** [tailwindlabs/tailwindcss-typography#232]
### What version of @tailwindcss/typography are you using?

v0.5.0

### What version of Node.js are you using?

v14.5.0

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/gomorizsolt/tailwindcss-typography-nuxtjs-bug

### Describe your issue

I'm not 100% sure if the issue has anything to do with the typography plugin itself, therefore feel free to point me to the right direction in case it doesn't fall under your radar...

## Issue

If the plugin is used in a Nuxt.js project, improper descendant selectors are generated. Examples:

```css
.prose :where(precode):not(:where([class~="not-prose"]*)) {
  /* ... */
}

.prose :where(tbodytr):not(:where([class~="not-prose"]*)) {
  /* ... */
}
```

- `precode` -> `pre code`
- `tbodytr` -> `tbody tr`

## Steps for reproduction
- Clone https://github.com/gomorizsolt/tailwindcss-typography-nuxtjs-bug
- `npm install`
- `npm run generate`
- inspect the generated styles inside of `dist/index.html`

## Workarounds

Set `target` option to `legacy` (which effectively disables the use of `:where()`).

## Questions

Any idea on how to get around it? Presumably it's kinda specific to Nuxt.js, but maybe someone has a clue...

**Comment by thecrypticace** [comment]
This is a weird one!

As best I can tell it's not tailwind doing this nor any other postcss plugin registered. I debugged the output from postcss and it did not have `:where(precode)` but it is indeed present in the html. I suggest opening an issue with Nuxt to see if they can track it down. Hopefully they can figure out what's going on 🤞
