### ISSUE TITLE
`tfoot td` are not styled

### ISSUE THREAD

**Issue by unindented** [tailwindlabs/tailwindcss-typography#242]
### What version of @tailwindcss/typography are you using?

v0.5.1

### What version of Node.js are you using?

v16.13.2

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

https://codepen.io/unindented/pen/zYPrJZd

### Describe your issue

If you've got a CMS that generates a `tfoot` tag for table footers, the `td`s contained in it are not aligned with the `td`s in `tbody`.

**Comment by unindented** [comment]
Respectful ping @adamwathan.

**Comment by adamwathan** [comment]
Thanks, will get to it when we get to it, have a lot of higher priority projects going on at the moment. Can solve this for yourself in userland using the customization API in the mean time 👍🏻
