### ISSUE TITLE
Safelisting prose classes with regex

### ISSUE THREAD

**Issue by gizburdt** [tailwindlabs/tailwindcss-typography#248]
### What version of @tailwindcss/typography are you using?

0.5.2

### What version of Node.js are you using?

17.4.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

https://github.com/gizburdt/prose

### Describe your issue

Hi,

We're building a theme builder, so we have variables coming from config and database.
Because of that we can't always write a full css class in code, like `prose-p:text-white`. 
"white" is coming from the database. It can also be "primary", "secondary" or "black"

So I would like to safelist this class: `prose-p:text-*`. Like so: `{ pattern: /prose-p:text-./ }`.
But this has no effect. When I try to safelist `prose-p:text-white` or `text-white` as string, both work.

So, like this:
```
safelist: [
    'text-white', // works
    'prose-p:text-white', // works
    { pattern: /^prose-p:text-.*/ }, // doesn't work
],
```

Mix throws a warning: `The safelist pattern `/prose-p:text-./` doesn't match any Tailwind CSS classes.`

Am I doing something wrong or is this maybe a bug?

Thanks! :)

**Comment by adamwathan** [comment]
Hey! You want this:

```
safelist: [
  {
    pattern: /^text-.*/,
    variants: ['prose-p'],
  },
],
```

Explained here: https://tailwindcss.com/docs/content-configuration#using-regular-expressions
