### ISSUE TITLE
`ol` and `ul` keys are duplicated in `styles.js`, resulting in some styles not being applied

### ISSUE THREAD

**Issue by unindented** [tailwindlabs/tailwindcss-typography#250]
### What version of @tailwindcss/typography are you using?

master

### What version of Node.js are you using?

v16.13.2

### What browser are you using?

N/A

### What operating system are you using?

N/A

### Reproduction repository

https://github.com/tailwindlabs/tailwindcss-typography

### Describe your issue

`ol` and `ul` keys are duplicated in `styles.js`, so the second occurrence overrides the first one, and margins never end up being applied. You can see it in the demo site:

<img width="1010" alt="Screen Shot 2022-02-20 at 8 25 16 AM" src="https://user-images.githubusercontent.com/69485/154852874-52de23d1-c3ee-4033-a220-b4d7c8ec23f0.png">

**Comment by lukens** [comment]
Any timeline for when this fix will go live?
