### ISSUE TITLE
Duplicate key in styles.js

### ISSUE THREAD

**Issue by hangtwenty** [tailwindlabs/tailwindcss-typography#253]
### What version of @tailwindcss/typography are you using?

0.5.2

### Describe your issue

I was looking at the source to figure out overrides, and I noticed duplicate `ol` and `ul` keys in the `base` section of `styles.js`:

https://github.com/tailwindlabs/tailwindcss-typography/blob/v0.5.2/src/styles.js#L96-L116

**Comment by reinink** [comment]
Hey there, this has been fixed (e50b7447602f8b34c704ccac98689d20d58eb598), and will be included with the next release 👍

If you need it right away, you can use the insiders channel: https://www.npmjs.com/package/@tailwindcss/typography?activeTab=versions

Thanks for reporting!
