### ISSUE TITLE
Not working on Safari 13.1.3 and Edge 87

### ISSUE THREAD

**Issue by Folyd** [tailwindlabs/tailwindcss-typography#255]
### What version of @tailwindcss/typography are you using?

The latest version typography installed by Tailwind standalone CLI

### What version of Node.js are you using?

No Node.js. I'm using the latest Tailwind standalone CLI

### What browser are you using?

Safari and Edge

### What operating system are you using?

macOS 10.15.7

### Reproduction repository

https://play.tailwindcss.com/uj1vGACRJA?layout=preview

### Describe your issue

I'm using the Tailwind standalone CLI (install from [here](https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.0.23)) and the typography plugin. Anything works perfectly on Chrome and Firefox, but not working well on Edge and Safari.

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/3369694/156920355-a49946ff-4090-4fb4-8554-741f7cd2cb82.png">

> Chrome works well

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/3369694/156920380-7561d0b2-fcf3-4aea-a576-ca23cd043467.png">

> Safari not working well

Even though, the Tailwind Typography demo page not working well on Safari. https://play.tailwindcss.com/uj1vGACRJA?layout=preview

**Comment by Folyd** [comment]
I found the reason: the typograph CSS uses a lot of `:where()` selectors, which get supported until Safari 14 and Edge 88.
https://developer.mozilla.org/en-US/docs/Web/CSS/:where

<img width="823" alt="image" src="https://user-images.githubusercontent.com/3369694/156920921-1fea4c76-e438-448f-a91c-3bf993c61739.png">

Can we have a good workaround to fix this?

**Comment by reinink** [comment]
Hey there!

So yes, as you discovered this plugin uses the `:where` pseudo-class to reduce the specificity of the selectors, making it possible to easily override typography styles with utilities.

If you need to support older browsers that [don't have support](https://caniuse.com/mdn-css_selectors_where) for the `:where` pseudo-class, such as Safari 13 (and older), you can disable this behavior using the `target` option:

```js tailwind.config.js
module.exports = {
  theme: {
    // ...
  },
  plugins: [
    require('@tailwindcss/typography')({
      target: 'legacy', // disables :where() selectors
    }),
  ]
  ...
}
```

Hope that helps! 👍
