### ISSUE TITLE
Add empty 'p' object to DEFAULT to fix '[class~=lead]' cascade error

### ISSUE THREAD

**Issue by rbjack** [tailwindlabs/tailwindcss-typography#256]
### What version of @tailwindcss/typography are you using?

0.5.2

### What version of Node.js are you using?

12.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/tailwindlabs/tailwindcss-typography/blob/master/src/styles.js#L1240

### Describe your issue

The missing `p: {},` from the DEFAULT settings is causing the paragraph margin to override the '.lead' class.

**Comment by thecrypticace** [comment]
I created a reproduction in Tailwind Play here: https://play.tailwindcss.com/4xkhjPpd3O

There does appear to be a difference between using `<p>` tags with the lead class and `<div>` tags because of the margin even though it's quite small. Will discuss this and see what we can figure out. Thanks!
