### ISSUE TITLE
Too much space between image and figcaption in base prose class

### ISSUE THREAD

**Issue by MichaelAllenWarner** [tailwindlabs/tailwindcss-typography#257]
### What version of @tailwindcss/typography are you using?

v0.5.2

### What version of Node.js are you using?

v16.4.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/uj1vGACRJA

### Describe your issue

NB: I used the official Typography demo URL as the "Reproduction repository," and the screenshots below are taken from that demo.

In the base `.prose`, there's a lot of space between image and figcaption in a figure:

![Screen Shot 2022-03-18 at 11 50 37 AM](https://user-images.githubusercontent.com/44578578/159036747-2d887207-f517-4221-ba42-a681dafd479e.png)

I believe this is not intended, as with `.prose-lg` it looks like this:

![Screen Shot 2022-03-18 at 11 51 57 AM](https://user-images.githubusercontent.com/44578578/159036996-7c20f4c9-36d1-4dc2-b058-4f113ac80a9e.png)

I think there's a zero-vertical-margin rule on the image that's losing the specificity battle in `.prose` but winning it in `.prose-lg`.

**Comment by JeanLucEsser** [comment]
Somehow related to the same spacing issue, I'm adding this here, while we're at it.

When using the `picture` tag inside `figure`, which should be common practice, prose does not apply its classes to `figure`, `img` and `figcaption`.

```
  <figure>
    <picture>
      <source
        type="image/webp"
        sizes="100vw"
        srcset="..."
      />
      <img
        src="..."
        srcset="..."
        sizes="100vw"
      />
      <figcaption>...</figcaption>
    </picture>
  </figure>
```
