### ISSUE TITLE
'Adding custom color themes', exactly like in the documentation, doesn't generate custom prose theme.

### ISSUE THREAD

**Issue by RemoteDevMac** [tailwindlabs/tailwindcss-typography#270]
### What version of @tailwindcss/typography are you using?

0.5.2

### What version of Node.js are you using?

v16.14.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

See description

### Describe your issue

Following what is in the documentation regarding adding a custom colour theme, it does not seem to generate the actual new `prose` theme. I am able to reproduce this with a completely clean, minimal project.

For demonstration purposes, below is the snippet from the documentation, but with the theme, name changed to `tiger`. This way it doesn't interfere with the legacy `prose-pink`.

**HTML**
```
<div class="prose prose-tiger">
  <p>text</p>
  <strong>bold text</strong>
  <a href="#">link</a>
</div>
```

**tailwind.config.js**

```
module.exports = {
  theme: {
    extend: {
      typography: ({ theme }) => ({
        tiger: {
          css: {
            '--tw-prose-body': theme('colors.pink[800]'),
            '--tw-prose-headings': theme('colors.pink[900]'),
            '--tw-prose-lead': theme('colors.pink[700]'),
            '--tw-prose-links': theme('colors.pink[900]'),
            '--tw-prose-bold': theme('colors.pink[900]'),
            '--tw-prose-counters': theme('colors.pink[600]'),
            '--tw-prose-bullets': theme('colors.pink[400]'),
            '--tw-prose-hr': theme('colors.pink[300]'),
            '--tw-prose-quotes': theme('colors.pink[900]'),
            '--tw-prose-quote-borders': theme('colors.pink[300]'),
            '--tw-prose-captions': theme('colors.pink[700]'),
            '--tw-prose-code': theme('colors.pink[900]'),
            '--tw-prose-pre-code': theme('colors.pink[100]'),
            '--tw-prose-pre-bg': theme('colors.pink[900]'),
            '--tw-prose-th-borders': theme('colors.pink[300]'),
            '--tw-prose-td-borders': theme('colors.pink[200]'),
            '--tw-prose-invert-body': theme('colors.pink[200]'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.pink[300]'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.pink[400]'),
            '--tw-prose-invert-bullets': theme('colors.pink[600]'),
            '--tw-prose-invert-hr': theme('colors.pink[700]'),
            '--tw-prose-invert-quotes': theme('colors.pink[100]'),
            '--tw-prose-invert-quote-borders': theme('colors.pink[700]'),
            '--tw-prose-invert-captions': theme('colors.pink[400]'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.pink[300]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.pink[600]'),
            '--tw-prose-invert-td-borders': theme('colors.pink[700]'),
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    // ...
  ],
}
```

The result is that there is no prose-tiger class generated for me.

Am I missing something? Is the documentation outdated or wrong? Or is this a legitimate bug in v0.5.2?

**Comment by adamwathan** [comment]
Hey! Just copied your exact code and it works as expected:

https://play.tailwindcss.com/Bp4FeqG7Hu

If this is still an issue after looking at that example, please open a new issue but include a reproduction next time 👍 As mentioned in the issue template a reproduction is required when opening an issue.

**Comment by ErwinAI** [comment]
Thank you for your quick response @adamwathan !

I've checked your example and it seems to work as intended. I copied my entire config in Tailwind Play (didn't know about that, it's awesome!) To be sure and it still works as intended. The class is not generated in my own project, however. It's not purged (safe listed it to make sure), so what remains is the `nuxt/tailwindcss` plugin. I'll see what's going on there.

**Comment by ErwinAI** [comment]
In case anyone stumbles upon this and uses `nuxt/tailwindcss` as well: try to remove the `dist` folder and `node_modules`. I think it was some sort of cache problem. It works as intended for me now!

**Comment by Kvintus** [comment]
> In case anyone stumbles upon this and uses `nuxt/tailwindcss` as well: try to remove the `dist` folder and `node_modules` and then install / run your project again. I think it was some sort of cache problem. It works as intended for me now!

In case anyone stumbles upon this... Applies for Next as well.
