### ISSUE TITLE
Strong inside <a> causes rendering issues

### ISSUE THREAD

**Issue by surjithctly** [tailwindlabs/tailwindcss-typography#275]
### What version of @tailwindcss/typography are you using?

3.1.0

### What version of Node.js are you using?

v16.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

https://play.tailwindcss.com/VTb5NkiKvQ

### Describe your issue

I have a simple usecase where `<strong>` tag is inserted inside `<strong><a>` but this doesn't display as expected. 

I have given `prose-violet` and also `prose-a:text-violet-500` but the color renders as black except the underline. 

The sample code:

```html
<div class="prose prose-violet prose-a:text-violet-500 p-16"> 
  <p>
    <strong>It is recommended to go through</strong>
    <a href="#" rel="noopener" target="_blank">
      <strong>Rollup's plugin documentation</strong>
    </a>
    <strong>first before reading the sections below.</strong>
  </p>
</div>

```
The current result. 
<img width="599" alt="image" src="https://user-images.githubusercontent.com/1884712/178274394-7fdc62d2-54aa-451a-8fe9-6369d021f14f.png">

Expected Result:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/1884712/178274783-8c45bc05-e1f5-4259-9917-1e1c1e0ec8d9.png">

Live reproducible demo on Tailwind Play
https://play.tailwindcss.com/VTb5NkiKvQ

Thank you!

**Comment by thecrypticace** [comment]
Gonna be thinking this one through some today but as a quick fix you can add the following to your CSS to work around the problem:
```css
.prose :where(strong):not(:where([class~="not-prose"] *)) {
  color: inherit;
}
```

**Comment by adamwathan** [comment]
> Do we really need a color variable for strong since it can be inherited from the parent? Not sure!

The main reason we do this is because `<strong>` tags have a different color than regular paragraph text in our default CSS (strong text is darker).

Probably can come up with a way to make this not happen by default though.

**Comment by reinink** [comment]
@surjithctly Hey thanks for reporting this. We've just made an update to this plugin where the `strong` and `code` color styles now inherit from their parent. I think this is generally a better default for these styles, and you can still override them if needed by adding custom styles 👍

**Comment by surjithctly** [comment]
Thank you 🙏
