### ISSUE TITLE
Unable to unset max width on child element

### ISSUE THREAD

**Issue by stephendolan** [tailwindlabs/tailwindcss-typography#286]
### What version of @tailwindcss/typography are you using?

0.5.7

### What version of Node.js are you using?

v16.8.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/stephendolan/site, see https://stephendolan.com/writing/automatic-birthday-reminders-in-omnifocus where the code block is cut off

### Describe your issue

This very well could be a misunderstanding of basic CSS, but I've Googled and tried different solutions for about an hour with no luck 😢 

I've left my site prose with the default max with of `max-w-prose`, but would like for code blocks to take up as much room as necessary, up to the width of the screen.

To do this, I added a `prose-code:!max-w-none` to my top-level `<article>` elements:
https://github.com/stephendolan/site/blob/main/src/_layouts/prose.liquid

When I inspect the HTML, it looks like the override is taking precedence and is active. However, if I uncheck the inactive default `65ch` max-width rule, the code block expands as expected (along with all of the other prose elements)!

![CleanShot 2022-09-15 at 17 12 50](https://user-images.githubusercontent.com/6677875/190509738-0b1e02e1-10f7-410e-89ff-22d07fd7f416.png)

To make sure it's not something code-block-specific, I added the same override to `<p>` tags with `prose-p:!max-w-none` and can verify that it also doesn't reset the max width.

**Comment by adamwathan** [comment]
Hey @stephendolan, good to see you hear! So what you're seeing here is just kinda normal HTML/CSS behavior — the child elements can't expand to be bigger than the parent.

https://play.tailwindcss.com/A8EIw2AjNI

![image](https://user-images.githubusercontent.com/4323180/190527096-68690554-de0f-4b0b-9d19-226a6c4ecb40.png)

The `<article>` element has a max-width, so the children are constrained to that max-width as well, even if they don't have a max-width of their own. The usual trick for this is to add a negative margin to the child you want to "break out" but it can be tricky to get it to work just right depending on the situation.

I don't have enough time right now to give you a solution to your specific problem but I would recommend asking in our Discord or in our GitHub Discussions, those are better places to get CSS specific help like this 👍 

Hope that at least explains the behavior you're seeing! 🍻

**Comment by stephendolan** [comment]
Thanks, Adam! I feel silly for not knowing that or setting up a simpler basic Tailwind layout to test it.

Just in case someone stumbles across this, I was able to get something that looks and feels nice by simply adding `prose-pre:lg:-mr-96`.
