### ISSUE TITLE
`not-prose` causes animation issues on Chrome

### ISSUE THREAD

**Issue by domdomegg** [tailwindlabs/tailwindcss-typography#295]
### What version of @tailwindcss/typography are you using?

v0.5.9

### What version of Node.js are you using?

v18.12.1

### What browser are you using?

Chrome 108.0.5359.124

### What operating system are you using?

Linux

### Reproduction repository

https://play.tailwindcss.com/Qyn1nMR7Gw

### Describe your issue

`not-prose` introduces CSS selectors that use complex `:where` clauses. In Chrome, this results in animations failing to run for the first ~0.5s of page load while it digests these clauses.

I think this is related to https://bugs.chromium.org/p/chromium/issues/detail?id=1407172. However, I thought I'd report it here as well given there is precedent for Tailwind [previously tracking related browser bugs](https://github.com/tailwindlabs/tailwindcss/issues/1402), and hopefully avoids others searching for this problem.

**Comment by adamwathan** [comment]
Hey thanks for reporting, I've escalated this one with my contacts on the Chrome team so we'll see where it goes!

**Comment by reinink** [comment]
Hey! I'm going to close this one as there isn't much more we can do at this point, and there's already an open issue for this with the Chromium team. Thanks either way for bringing it to our attention 👍
