### ISSUE TITLE
Feature request: Change color on plugin level

### ISSUE THREAD

**Issue by MrMacStripe** [tailwindlabs/tailwindcss-typography#33]
First of all, thank you for the plugin! I think it will generate a lot of value for me in the future.

I would love to see a text color palette that can be altered for all the prose instances in one place of the config. 
Right now we have:

```
default: {
    css: [
      {
        color: defaultTheme.colors.gray[700],
        maxWidth: '65ch',
        '[class~="lead"]': {
          color: defaultTheme.colors.gray[700],
        },...
```

Instead I propose something like

```
colors: {
      prose-theme-x: {
        100: "#fffaf0",
        200: "#feebc8",
        300: "#1a202c",
        400: "#f6ad55",
        500: "#ed8936",
        600: "#dd6b20",
        700: "#c05621",
        800: "#9c4221",
        900: "#7b341e",
      },

default: {
    css: [
      {
        color: colors.prose-theme-x[700],
        maxWidth: '65ch',
        '[class~="lead"]': {
          color: colors.prose-theme-x[700],
        },...
```

Sure it's easy to just replace all instances of default.Theme.colors.grey but then I need to add a whole lot of options to the config file. If I could just edit the color palette in the config instead it would be cleaner and easier in my opinion.

Let me know what you think, looking forward!

**Comment by LionsAd** [comment]
https://github.com/tailwindlabs/tailwindcss-typography/issues/90 is related to this, but proposes a different approach.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

We currently have color modifiers https://github.com/tailwindlabs/tailwindcss-typography#color-modifiers they will modify the color of links for example so that your prose still looks good, but has a bit of theming as well!

Here is an example: https://play.tailwindcss.com/JvbI95HPx6
