### ISSUE TITLE
Adding tailwind prose class seems to change behavioural z-index of lists

### ISSUE THREAD

**Issue by amykble** [tailwindlabs/tailwindcss-typography#34]
https://loving-hawking-9f743b.netlify.app/blog/using-a-html-img-tag/ <- example of issue, if you remove z-10 from the nav, the list items appear on top of it

I'm using Vue and Gridsome, removing the prose classes stops the behaviour, it happens with both unordered and ordered lists

The Navigation bar has a fixed position but no z-index is being applied to it

I can't see any z-index being applied to the lists when the prose class is being used but I could have missed something

It could be something to do with the absolute positioning of list elements

**Comment by johnmendonca** [comment]
I added prose to one of my pages and now <li> content appears above my menu dropdowns.  It has something to do with this style:

```
.prose ul > li {
    position: relative;
}
```

When you add `z-index: -1;` to the above, the list items go back where they belong.

[Screenshot of the issue](https://imgur.com/pGWFdaT.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

When you have `ul/li` items in your prose, we add `position: relative;` so that we can position the small dots before each list item with `position: absolute;`. The `position: relative` will create a new "layer" therefore it now seems to be on top.

A possible fix for us could be adding a `relative` on the `prose` class itself. However this will result in the full `prose` block be on top of your navigation.

So what I would suggest is to add a `z-10` to your navbar and it should be good to go. Here is an example: https://play.tailwindcss.com/OGofKqUFIM

**Comment by marbaque** [comment]
It feels like the lists approach is very problematic, if for instance you want to modify only one list inside a prose div, then you need to address different media queries and elements in order to override it

**Comment by lukens** [comment]
I agree the lists approach is problematic. It feels wrong that we should need to update the style of other elements to prevent list items appearing over them.

I put the following overrides in my `windi.config.js`, which puts the markers in the same position for me, without the issue of them becoming a new layer that sits on top:

```javascript
export default {
    theme: {
        extend: {
            typography: {
                DEFAULT: {
                    css: {
                        "ul > li": {
                            "position" : "unset",
                            "&::before" : {
                                "position" : "unset !important",
                                "float" : "left",
                                "margin-left": "-1.5em",
                                "margin-top": ".75em",
                            }
                        }
                    },
                },
            },
        },
    },
    plugins: [
        require('windicss/plugin/typography'),
    ],
}
```

The positioning via the margins isn't an exact science though (just seemed to put them in the same place for me), so YMMV).
