### ISSUE TITLE
Prose class adds inner border to specific font on Chrome

### ISSUE THREAD

**Issue by sanderjn** [tailwindlabs/tailwindcss-typography#347]
### What version of @tailwindcss/typography are you using?

0.5.12

### What version of Node.js are you using?

Tailwind Play version

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/UzZoqwcYFH

### Describe your issue

I've had to use a specific font from Adobe Fonts, and when using the Typography plugin, this font shows some kind of inner border on the letter W. This only happens in Chrome and doesn't happen when there is no `prose` class. I've never had this issue with other fonts.

![CleanShot 2024-04-15 at 13 35 42@2x](https://github.com/tailwindlabs/tailwindcss-typography/assets/32776165/eb35b238-1427-480e-8631-e8faf7f75898)

See [https://play.tailwindcss.com/UzZoqwcYFH](https://play.tailwindcss.com/UzZoqwcYFH) for an example.

I couldn't find out which CSS rule(s) cause this.

**Comment by hkan** [comment]
Not an inherent issue with the plugin itself. The font has no support for font weights other than 400, but the plugin sets `font-weight: 800` for all headings. This can be overcome by adding `prose-headings:font-normal` to the prose container.

**Comment by sanderjn** [comment]
> Not an inherent issue with the plugin itself. The font has no support for font weights other than 400, but the plugin sets `font-weight: 800` for all headings. This can be overcome by adding `prose-headings:font-normal` to the prose container.

Ah great find! Thanks.

So it's not a bug. Will close the issue.
