### ISSUE TITLE
Different rendering on Firefox

### ISSUE THREAD

**Issue by florianbouvot** [tailwindlabs/tailwindcss-typography#349]
### What version of @tailwindcss/typography are you using?

v0.5.12

### What version of Node.js are you using?

v21.7.3

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/qyhX006OCq

### Describe your issue

Hi Tailwind team,

I find a rendering issue between Firefox and others browser.
If you add a `br` in an `li` it add space between text lines on Firefox but not on Chrome and Safari.

![Capture d’écran 2024-04-23 à 10 40 11](https://github.com/tailwindlabs/tailwindcss-typography/assets/2061540/8c1ce3f5-03de-41d2-aa42-a8185f4e42ba)

_Firefox / Chrome (see first list item)_

It may be a problem with Firefox and not Tailwind 🤷‍♂️

Thanks, Florian

**Comment by thecrypticace** [comment]
It's very odd that FF is allowing margins on `<br>` here. I've merged a fix in #350. Will tag a release in the am!

**Comment by florianbouvot** [comment]
Thank you @thecrypticace
