### ISSUE TITLE
PurgeCSS erases some heading rules

### ISSUE THREAD

**Issue by albertmolodec** [tailwindlabs/tailwindcss-typography#35]
Hello.

I use 11ty with TailwindCSS and I faced a problem. Look, I set class `prose` on the article in my `post.njk` template:

```njk
{% block content %}
    <article class="prose">
        <h1>{{ title }}</h1>
        {{ content | safe }}
    </article>
    ...
{% endblock %}
```

Content in markdown files may contain tier 1-4 headings. After build, the resulting css includes `.prose h1` and `.prose h3` but doesn't contain `.prose h2` and `.prose h4`. Although this page has only level 2 headings.

![image](https://user-images.githubusercontent.com/26366132/88150829-53c7ae80-cc1b-11ea-864b-4b0393b73ddd.png)
![image](https://user-images.githubusercontent.com/26366132/88150858-5c1fe980-cc1b-11ea-94ad-df9473aa5dff.png)

I tried to add `'prose'` to whitelist but it didn't work:

```js
purge: {
    enabled: process.env.ELEVENTY_ENV === 'production',
    content: [
      './src/**/*.njk',
      './src/**/*.md',
      './src/**/*.js',
      './src/**/*.svg',
    ],
    options: {
      whitelist: ['mode-dark', 'prose'],
    },
  },
plugins: [
  require('@tailwindcss/typography'),
```

In development mode everything works.

Do anybody knows where might be a problem?

**Comment by flemay** [comment]
I have similar problem especially for responsive classes such as `lg:prose-lg`. I don't have `.lg\:prose-lg h2`, `.lg\:prose-lg pre`, etc.

I ended up having this config for `tailwind.config.js`:

```js
module.exports = {
  purge: {
    mode: 'all',
    content: [
      'layouts/**/*.html'
    ],
    options: {
      whitelist: ['h2', 'pre', 'code']
    }
  },
  variants: {},
  plugins: [
    require('@tailwindcss/typography')
  ]
}
```

and my `main.css` to be:

```css
/* purgecss start ignore */
@tailwind base;
@tailwind components;
/* purgecss end ignore */

@tailwind utilities;
```

So I am wondering what is the best way to use `PurgeCSS` with `tailwindcss-typography`.

**Comment by oxalorg** [comment]
I'm also having issues with `PurgeCSS`. I am only using `prose` and `prose-xl` classes in my html, but prugecss is not removing the other prose classes (`sm lg 2xl`) from the production build.

**Comment by lowv-developer** [comment]
Typography plugin needs tailwindcss v1.50
https://github.com/tailwindlabs/tailwindcss-typography/pull/43

**Comment by flemay** [comment]
I've updated my previous comment to include the dependencies. Using tailwindcss 1.5.2 still strips out classes such as `.lg\:prose-lg h2` which I need to include in the whitelist.

**Comment by lowv-developer** [comment]
yeah you right, I have some issues myself with 1.5.2 and class .prose table tr
maybe the solution would be in this direction https://github.com/tailwindlabs/discuss/issues/250

can we import prose somehow in the scss file so then we can do purgecss start ignore?

**Comment by lowv-developer** [comment]
this done the work in purgecssOptions:

whitelistPatternsChildren: [/prose$/],

**Comment by flemay** [comment]
Thanks, @lowv-developer! It did work! 👍

**Comment by 0x2E** [comment]
> 
> 
> I'm also having issues with `PurgeCSS`. I am only using `prose` and `prose-xl` classes in my html, but `purgecss` is not removing the other prose classes (`sm lg 2xl`) from the production build.
> 
> So my `20kb` css file ends up over `120kb` because of this issue.

@oxalorg You may need to manually disable unused modifiers. After I turned off all modifiers except `default` according to [Disabling size modifiers](https://github.com/tailwindlabs/tailwindcss-typography#disabling-size-modifiers), the file dropped from 86KB to 33KB. But this is not small enough. Chrome told me that there are still 78% useless css. I suspect purgecss did not clean up @tailwindcss/typography.

**Comment by huphtur** [comment]
Ran into the same problem with Eleventy, my solution was to run 11ty first and then run Tailwind:

purge settings in `tailwind.config.js`:
```javascript
purge: {
  mode: 'all',
  content: ['_site/**/*.html'],
},
```

build command in `package.json`:
```javascript
"build": "eleventy && NODE_ENV=production postcss src/css/tailwind.css --o _site/css/style.css"
```

The only downside (that I know so far) is that you can't [inline css](https://www.11ty.dev/docs/quicktips/inline-css/).

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

By default purge will purge everything that it can't find. Essentially if you build the markdown files, and `<h2>` is not present then it will remove `.prose h2`. If your markdown content is coming from some form database/API, then you would have to safelist all the `.prose` related styles (because you don't know what you will get from your DB/API).

You can use the `/prose$/` regex that @lowv-developer provided.

Also see: https://tailwindcss.com/docs/optimizing-for-production#purge-css-options
