### ISSUE TITLE
Is there a way to define the same style for multiple headings?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [tailwindlabs/tailwindcss-typography#37]
Do I need to setup the config for each heading element one by one or is there a way to do them all together if the styles repeat?

```
                    h1: {
                        color: '#e0e0ff',
                    },
                    h2: {
                        color: '#e0e0ff',
                    }
```

**Comment by estevanmaito** [comment]
You need to setup one by one, as that is the way they are configured: https://github.com/tailwindlabs/tailwindcss-typography/blob/master/src/styles.js#L68

**Comment by adamwathan** [comment]
You can combine them, it's just CSS:

```
'h1, h2, h3': { color: 'purple' }
```

**Comment by abishekrsrikaanth** [comment]
@adamwathan, thanks. Does that mean, I can add custom styles like 

For example:
```
   'div.ql-video': {
      width: '100%',
      height: '400px'
        }
```

**Comment by benji014628** [comment]
> @adamwathan, thanks. Does that mean, I can add custom styles like
> 
> For example:
> 
> ```
>    'div.ql-video': {
>       width: '100%',
>       height: '400px'
>         }
> ```
> 
> Just trying to figure out how to set styles for a video on a blog post that uses quill js. Quill JS adds its own css classes to the elements, so a bit confused about how to use it. I am hoping it makes sense

did you try it first?

**Comment by RobinMalfait** [comment]
> @adamwathan, thanks. Does that mean, I can add custom styles like
> 
> For example:
> 
> ```
>    'div.ql-video': {
>       width: '100%',
>       height: '400px'
>         }
> ```
> 
> Just trying to figure out how to set styles for a video on a blog post that uses quill js. Quill JS adds its own css classes to the elements, so a bit confused about how to use it. I am hoping it makes sense

Yep, this works. It will resolve to `.prose div.ql-video`.

**Comment by CanRau** [comment]
> You need to setup one by one, as that is the way they are configured: https://github.com/tailwindlabs/tailwindcss-typography/blob/master/src/styles.js#L68

That worked, was expecting 
```ts
DEFAULT: {
  css: {
    headings: {
      fontWeight: "unset",
    },
```
this to just work as `prose-headings:{utility}` exists, but it's not a big deal
