### ISSUE TITLE
Could not find a declaration file for module '@tailwindcss/typography'.

### ISSUE THREAD

**Issue by txndai** [tailwindlabs/tailwindcss-typography#38]
>Could not find a declaration file for module '@tailwindcss/typography'. 'c:/Users/fari/Documents/GitHub/easybank-tailwind->template/node_modules/@tailwindcss/typography/src/index.js' implicitly has an 'any' type.
 >Try `npm install @types/tailwindcss__typography` if it exists or add a new declaration (.d.ts) file containing `declare module >'@tailwindcss/typography';`ts(7016)

The suggested fix works, is there a reason why the .d.ts file isn't included in the root of the typography folder by default?

**Comment by adamwathan** [comment]
There is no .d.ts file to include in the root, just doesn't exist at all 😅 probably not something we'll add either, it's not written in TypeScript and neither is Tailwind.

**Comment by txndai** [comment]
I think it might be my bundling process that's the problem, faced the same issue with another npm module 😅

**Comment by Kosai106** [comment]
@adamwathan Tailwind now provides TS types - Can this be re-evaluated? 👀
