### ISSUE TITLE
Add lodash to dependencies

### ISSUE THREAD

**Issue by redxtech** [tailwindlabs/tailwindcss-typography#39]
Hey!

When I've been using this in one of my projects I had to install lodash as a separate dependency, as without it my app wasn't even starting. Now that I have it installed, I'm getting this warning from node:
```
(node:1863470) [MODULE_NOT_FOUND] Error: @tailwindcss/typography tried to access lodash, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(Use `node --trace-warnings ...` to show where the warning was created)
```

Is there a reason for this? Or am I missing something?

**Comment by estevanmaito** [comment]
Did you install `tailwindcss`?

Because it is a `peerDependency` of `typography` and it has `lodash` as a dependency, which would avoid this error.

**Comment by redxtech** [comment]
Yes, I have `tailwindcss` install. I would imagine that everyone who's using typography would, as it's a plugin for that.

**Comment by estevanmaito** [comment]
Could you create a reproduction repository?

**Comment by redxtech** [comment]
Sorry for the late reply - you can see if happening in this repo here: https://github.com/redxtech/when-next

**Some details:**
Yarn version: berry
Node version: 14.7.0
Tailwindcss version: 1.6.2
Typography plugin version: 0.2.0

**Comment by redxtech** [comment]
It looks like this could be fixed by merging the `lodash-bugfix` branch already existing on this repo.

**Comment by jlgeering** [comment]
same problem here - build fails when not using lodash

adding lodash to my project (`yarn add -D lodash`) changed it from a crash to a warning

**Comment by jlgeering** [comment]
created a PR from the existing branch: #65

**Comment by whmountains** [comment]
Yarn v2 detects this and refuses to proceed.

```
Error: @tailwindcss/typography tried to access lodash, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```
