### ISSUE TITLE
Does not apply in angular

### ISSUE THREAD

**Issue by adrian-goe** [tailwindlabs/tailwindcss-typography#40]
Hi, 
I have tried to use the plugin in Angular9.

As markdown interpreter I use [ngx-markdown](https://github.com/jfcere/ngx-markdown). Tailwind works, because the whole application was developed with Tailwind only.

But the plugin does not work.

component.html:
```html
<div class="w-11/12 px-4 mx-auto mt-4">
  <article class="prose prose-sm sm:prose lg:prose-lg xl:prose-xl bg-blue-100" ngPreserveWhitespaces markdown
           [src]="'assets/project/demo.md'" (load)="onLoad($event)" (error)="onError($event)">
  </article>
</div>
```

tailwind.config.ts
```ts
        typography: (theme) => ({
            default: {
                css: {
                    color: '#ffffff',

                    // ...
                }
            }
        }),
        variants: {},
        plugins: [
            require('@tailwindcss/typography')
        ],
```

I have tried the different ViewEncapsulation. Nothing worked.

The first idea I had was to add `::ng-deep`to every class. Is there a way to do that?
Or do you have a better idea?

**Comment by adamwathan** [comment]
Can you explain what you mean by "doesn't work"? Do the classes get generated? Did you inspect the generated HTML in dev tools to troubleshoot at all and if so what did you discover? Can you create a minimal reproduction of the problem so that I can pull it down to troubleshoot myself?

**Comment by adrian-goe** [comment]
Sure. My expectation is that I would have a styled blog. At least white text, since that's what I put in the theme. A table that looks similar to the one in your example. 
None of this is. 
A little hard to read on the dark background.

<img width="643" alt="Screenshot 2020-07-25 at 14 26 18" src="https://user-images.githubusercontent.com/17064122/88456986-21b88580-ce83-11ea-9bcc-70009b2dd4d6.png">

If I add in the `<article>` the class `text-gray-300`, the text is accordingly in the frame. but that's not how it should be, right?

No styles are added or applied in the browser.

The `prose` class is not generated. 

I can finish an example later, but I'm on my way.

**Comment by adrian-goe** [comment]
https://github.com/adrian-goe/minimal-reproduction

**Comment by RobinMalfait** [comment]
Hey @adrian-goe 

The issue with your code is that you have this:
https://github.com/adrian-goe/minimal-reproduction/blob/4592bdde495cfca098e56db6eaaac26301427f35/tailwind.config.js#L42-L45

You have `variants`, and `plugins` *inside* of the theme section instead of being a sibling.

```js
// What you have:
module.exports = {
  theme: {
    variants: {},
    plugins: []
  },
}

// Expected:
module.exports = {
  theme: {},
  variants: {},
  plugins: []
}
```
