### ISSUE TITLE
Feature request: Add ‘break-words’

### ISSUE THREAD

**Issue by RubenVanEldik** [tailwindlabs/tailwindcss-typography#44]
On smaller screens there are often words (especially links) that overflow. This is easily solved by adding the `.break-words` class. I have added them manually to my projects, but since it’s such a common issue for Typography sections I thought it might be handy to add it to the defaults. 

![Uploading 36BBC06C-725C-4C75-ACB3-04A9DBE3C646.png…]()

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

I think that this might become a bit too opinionated. If you don't want to add `break-words` to all the paragraphs, then you could do something like this: https://play.tailwindcss.com/jfWrGtgR8D?file=config

```js
module.exports = {
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            p: {
              '@apply break-words': '',
            },
          },
        },
      },
    },
  },
  variants: {},
  plugins: [require('@tailwindcss/typography')],
}
```
