### ISSUE TITLE
How can I disable .prose-generated classes for @tailwindcss/ui?

### ISSUE THREAD

**Issue by zaydek** [tailwindlabs/tailwindcss-typography#46]
Hello! 👋 I’m seeking to understand how I can disable `.prose`-generated classes when consuming the @tailwindcss/ui plugin? I suspect I can purge these classes, but that seems a little bit like overkill.

My config looks like this:

```js
module.exports = {
	purge: [
		"./public/**/*.html",
		"./src/**/*.js",
	],
	theme: {
		extend: {},
	},
	variants: {},
	plugins: [
		require("@tailwindcss/ui"),
	],
}
```

But I noticed I’m getting `.prose` classes in my generated file, my guess is because this plugin is bundled with Tailwind UI, which makes sense. But because if _I don’t need the prose classes_, I tried disabling it like this:

```js
module.exports = {
	purge: [
		"./public/**/*.html",
		"./src/**/*.js",
	],
	theme: {
		extend: {},
	},
	variants: {
		typography: [],
	},
	plugins: [
		require("@tailwindcss/ui"),
	],
}
```

This seems to help a little but that still generates the classes from what I can tell.

**Is there a way to prevent these classes from being generated in the first place if I’m using @tailwindcss/ui?** This would be greatly appreciated!

**Comment by codex-zaydek** [comment]
For what it’s worth I also tried these:

```js
	// ...
	plugins: [
		require("@tailwindcss/ui")({
			typography: false,
		}),
	],
  corePlugins: {
		typography: false,
  },
	// ...
```

Which unsurprisingly did nothing. 😅

**Comment by web2033** [comment]
I have a similar problem.
https://github.com/posva/vite-tailwind-starter/issues/74

Even with purge enabled and not using any prose related styles, it adds about 70kb to CSS output.

**Comment by web2033** [comment]
Seems fixed (don't know exactly when).
Currently:
```
    "@tailwindcss/ui": "^0.6.0",
    "tailwindcss": "^1.8.9",
```

**Comment by chadlittle** [comment]
Same issue here, prose sticks around after purge. Tailwind 1.8.10 and ui 0.6.2

**Comment by jussivirtanen** [comment]
Same issue here. Here are my dependencies:

```
"dependencies": {
  "@tailwindcss/ui": "^0.6.2",
  "autoprefixer": "^10.0.1",
  "postcss": "^8.1.1",
  "postcss-cli": "^8.0.0",
  "tailwindcss": "^1.8.10"
}
```

**Comment by vadimdemedes** [comment]
Uncommenting `future` section in `tailwind.config.js` helped me solve this:

```json
{
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true
  }
}
```

When you create a new config with `tailwindcss init`, these come commented by default.

**Comment by RobinMalfait** [comment]
If you didn't update to tailwind 2.0 yet then this should work as expected:

```js
module.exports = {
  // ...
  plugins: [
    require("@tailwindcss/ui")({ typography: false }),
  ]
}
```

Otherwise, the `@tailwindcss/ui` plugin is not needed anymore. See: https://tailwindui.com/changes-for-v2
