### ISSUE TITLE
Changing the font family causes inheritancy issues

### ISSUE THREAD

**Issue by chrish-d** [tailwindlabs/tailwindcss-typography#50]
I have my `tailwind.config.js` set up like this;

```js
const typography = require("@tailwindcss/typography");

module.exports = {
  theme: {
    fontFamily: {
      body: ["'Brandon Grotesque'", "sans-serif"],
    },
    typography: (theme) => ({
      default: {
        css: {
          color: theme("colors.black"),
          fontSize: "1rem",
          fontFamily: theme("fontFamily.body"),
        },
      },
    }),
  },
  plugins: [typography],
};
```

But when output, `.prose` looks like this;

```css
font-family: "Brandon Grotesque"; /* this gets overwritten */
font-family: sans-serif; /* by this */
```

What I'd expect would be this;

```css
font-family: "Brandon Grotesque", sans-serif;
```

**Comment by adamwathan** [comment]
Rewrite your overrides like this:

```js
const typography = require("@tailwindcss/typography");

module.exports = {
  theme: {
    fontFamily: {
      body: ["'Brandon Grotesque'", "sans-serif"],
    },
    typography: (theme) => ({
      default: {
        css: {
          color: theme("colors.black"),
          fontSize: "1rem",
          fontFamily: theme("fontFamily.body").join(", "),
        },
      },
    }),
  },
  plugins: [typography],
};
```

The return value of `theme` is an array of fonts, so you need to turn that into a string since the configuration for the typography plugin is just raw CSS overrides 👍

**Comment by chrish-d** [comment]
That solved it, thanks @adamwathan 

I'll keep the same technique in mind for anything else like this 👍

**Comment by adamwathan** [comment]
Not intuitive admittedly, sorry about that.

**Comment by terryupton** [comment]
I have just come across this issue today and took me a while to figure out.
@adamwathan could I suggest this is documented somewhere in the Typography Docs/Readme? 
I think it is a likely use-case as many sites will use custom fonts (Google, Adobe etc).

**Comment by adamwathan** [comment]
This will just work in Tailwind 2.0 which will be out in about 2 weeks 👍🏻

**Comment by Defite** [comment]
> This will just work in Tailwind 2.0 which will be out in about 2 weeks 👍🏻

Well, it's not working here.
