### ISSUE TITLE
Backticks appear around code blocks

### ISSUE THREAD

**Issue by richardherbert** [tailwindlabs/tailwindcss-typography#51]
The backtick character is being displayed around text marked as `code`. This also happens on the demo site https://tailwindcss-typography.netlify.app/

**Comment by adamwathan** [comment]
This is deliberate, you can override it in your customizations if you like by unsetting the "content" property on the before and after pseudo elements on "code" 👍🏻

**Comment by richardherbert** [comment]
Hummm, okay. It might be worth adding something to the docs (I'm happy to do that) and the reasoning why (someone else might have to do that). In my ignorance I thought it was broken. I'll have to research your advice on how to remove it. 

Thanks for the prompt response.

**Comment by richardherbert** [comment]
Apologies, I've re-read the docs again and seen your explanation.

**Comment by EricBusch** [comment]
For anyone else having this problem (including my future self), here's a [link to the default config file](https://github.com/tailwindlabs/tailwindcss-typography/blob/master/src/styles.js) and the changes I made to my tailwind.config.js file to remove the ticks from before and after code blocks.

```js
module.exports = {
    purge: {},
    important: true,
    theme: {
        extend: {},
        typography: {
            default: {
                css: {
                    'code::before': {
                        content: "",
                    },
                    'code::after': {
                        content: "",
                    },
                },
            },
        },
    },
    variants: {},
    plugins: [
        require('@tailwindcss/ui'),
    ],
}
```

**Comment by sebastian0119** [comment]
@EricBusch Thanks for the [explanation](https://github.com/tailwindlabs/tailwindcss-typography/issues/51#issuecomment-724877617). But I am not sure where to insert / modify this syntax.
The Typhoon theme already has a `./user/themes/typhoon/tailwind.config.js` file with most of the lines you show. Just adding the two pseudo-classes did not change the behaviour.
Thanks in advance :+1:
