### ISSUE TITLE
Issue including typography in a node project

### ISSUE THREAD

**Issue by jerrythomas** [tailwindlabs/tailwindcss-typography#53]
[Reproducible Code](https://github.com/jerrythomas/vue-tailwind)

I followed the instructions from [@tailwindcss/typography](https://github.com/tailwindlabs/tailwindcss-typography)

```
yarn add @tailwindcss/typography
```
added the plugin to tailwind.config.js as mentioned.

Shouldn't the following command generate a final CSS that contains the typography classes?

```bash
npx tailwindcss build src/styles/index.scss -o output.css
```
Adding the following line to the source file `index.scss` after `@tailwindcss base;` is not mentioned in the document.
`@tailwindcss typography;`

But even that makes no difference. This line is not replaced at all and is retained as is. Building the app using `yarn dev` and `yarn build` also does not include the typography styles in the app. This just the default app with only the addition of `tailwindcss`.

Can you tell me what I am doing wrong or what step I have missed?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

If you want to add plugins to tailwind, then you have to require them inside the `plugins: []` list in your `tailwind.config.js` file. You added `@tailwind typography;` but that doesn't exist.

The only things you have to do are:

1. Install the plugin
2. List the plugin in the `plugins` list
3. Add a `prose` class to style everything inside that element

https://github.com/tailwindlabs/tailwindcss-typography#installation
