### ISSUE TITLE
Overlaying text in Code Blocks when the language is specified

### ISSUE THREAD

**Issue by nikitattt** [tailwindlabs/tailwindcss-typography#54]
Hello! 

Here is the issue with the text in Code Blocks when language is specified, like this:
```
```html
```

It looks like there is another white coloured text layered before main with some shift:
![Image 2020-08-12 at 7 22 32 PM](https://user-images.githubusercontent.com/53146405/90014378-27aac500-dcd1-11ea-8287-570455cdf1f0.png)
Or like there is a white shadow on the text.

Here is the normal look(when language is not specified):
![Image 2020-08-12 at 7 21 08 PM](https://user-images.githubusercontent.com/53146405/90014296-00ec8e80-dcd1-11ea-9c99-407927d91f3d.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We don't have specific styling for syntax highlighting. So I am pretty sure that this is a bug with the syntax highlighter that you are using.

**Comment by adamwathan** [comment]
Just to piggy back, it's probably whatever CSS comes with your syntax highlighting plugin/theme (Prism, highlight.js, whatever). They are adding a text-shadow, I'm sure deliberately (Prism does this in several of their default themes). So your best bet is to override their CSS with the CSS you actually want, likely with some carefully placed `text-shadow: none` declarations.
