### ISSUE TITLE
Default list-style in unordered and order lists.

### ISSUE THREAD

**Issue by wildpow** [tailwindlabs/tailwindcss-typography#56]
![Screen Shot 2020-08-12 at 5 20 12 PM](https://user-images.githubusercontent.com/17464319/90080874-a0edec00-dcc0-11ea-8bc8-1e52133f3df7.png)
![Screen Shot 2020-08-12 at 5 20 16 PM](https://user-images.githubusercontent.com/17464319/90080880-a4817300-dcc0-11ea-8e7d-01b54205de02.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This seems like an issue when you forget to include to use the `base` styles of Tailwind itself. If you use the base styles (which includes a reset for it) then it should be fine. Going to close this for now.
