### ISSUE TITLE
Centering Images

### ISSUE THREAD

**Issue by samrobbins85** [tailwindlabs/tailwindcss-typography#58]
For images that don't take up the whole width, it might be good to centre images for better appearance

I implemented this in my CSS with
```css
.prose p img {
  @apply mx-auto;
  @apply block;
}
```

but might be worth merging into the plugin

**Comment by benji014628** [comment]
this is not an issue, its a feature request

**Comment by bniedermeyer** [comment]
For anyone coming across this via google - I was able to achieve this by applying a [customization](https://github.com/tailwindlabs/tailwindcss-typography#customization) in my `tailwind.config.js`

```
extend: {
      typography: {
        DEFAULT: {
          css: {
            img: {
              margin: 'auto',
            },
          },
        },
      },
    },
```

**Comment by katticot** [comment]
thx a lot @bniedermeyer , i really dont understand this feature request.

**Comment by alexhooley** [comment]
This can also be done with [Element Modifiers](https://tailwindcss.com/docs/typography-plugin#element-modifiers):

```html
<article class="prose prose-img:mx-auto">
  {{ markdown }}
</article>
```
