### ISSUE TITLE
Allow for custom styling within prose

### ISSUE THREAD

**Issue by samrobbins85** [tailwindlabs/tailwindcss-typography#62]
When using something like MDX you might want to add custom components in your markdown, however their style is influenced by the prose styling and it is not easy to remove this.

A possible solution to this is to use the `:not` pseudo-class as demonstrated in [this stackoverflow post](https://stackoverflow.com/questions/36355486/is-there-a-css-selector-for-element-without-any-class)

There is a possibility that some markdown processors will add classes to elements, so it might be best to have this as an option you can enable

**Comment by mathieutu** [comment]
duplicate of https://github.com/tailwindlabs/tailwindcss-typography/issues/32

**Comment by samrobbins85** [comment]
Oops, thanks for letting me know
