### ISSUE TITLE
Bold colour overwrites link styling

### ISSUE THREAD

**Issue by stephenafamo** [tailwindlabs/tailwindcss-typography#64]
If a link text is also bold, the `prose strong` styling gets a higher priority than `prose a` 

This means that bold links have no colour 😢 

![image](https://user-images.githubusercontent.com/13472455/90934759-292b6a00-e402-11ea-9b5a-fffb8d383af1.png)

**Comment by Healios** [comment]
I also have this issue...

I have been able to solve it by customizing prose in tailwind.config.js like so:
`strong: {
    color: "unset",
},`

The pertinent question though is, why does `.prose strong` even have a color? Should it not just have a weight, and only a weight?

**Comment by simonswiss** [comment]
Hey! Going to close this issue since this is not something that happens anymore with the new version of the Typography plugin, where we use flat selectors to apply styles.

**Comment by fabswt** [comment]
Let me know if I missed something, but I think this is still happening with v0.5.2.

With this HTML:

```html
<a href="https://bilingueanglais.com/blog/552/comment-comprendre-anglais-parle/"><strong>comprendre l'anglais oral</strong></a>
```

I get this CSS:

```css
.prose :where(strong):not(:where([class~="not-prose"] *)) {
    color: var(--tw-prose-bold);
    font-weight: 600;
}
```
where `--tw-prose-bold` is black and overwrites my link color.

Had to add this entry to tailwind.config.js to circumvent the issue:

```json
            '--tw-prose-bold': 'inherit',
```

**Comment by liyasthomas** [comment]
This issue still exists even in the latest version. Strong text has a `color: var(--tw-prose-bold)` attribute. Anybody found a fix?
