### ISSUE TITLE
Not always helpful to include " quotation marks for block-quote..what if you want to include source name?

### ISSUE THREAD

**Issue by jensamunch** [tailwindlabs/tailwindcss-typography#66]
![image](https://user-images.githubusercontent.com/1650140/92000395-c1e4b280-ed3d-11ea-9e67-60bc22a7a730.png)

**Comment by jensamunch** [comment]
I fixed in this way - dirty hack

```
module.exports = {
  plugins: [
    require('@tailwindcss/ui'),
    require('@tailwindcss/typography'),
  ],
  important: true,
  future: {
  },
  experimental: {
    uniformColorPalette: true,
  },
  theme: {
    typography: {
      default: {
        css: {
          color: '#1d1d1f',
          'h1, h2, h3': {
            fontWeight: '800',
          },
          p: {
            '&::before': {
              content: 'none !important',
            },
            '&::after': {
              content: 'none !important',
            },
          },
        },
      },
```

**Comment by mathieutu** [comment]
you also can set false to disable it:

```js
'blockquote p:first-of-type::before': false,
'blockquote p:last-of-type::after': false,
```

**Comment by benji014628** [comment]
There's any easier way to solve this... use the span element

**Comment by RobinMalfait** [comment]
Hey! Thank you for your issue!
Much appreciated! 🙏

The typography has more opinions compared to our other plugins. In case you don't want those quotes, you can unset them inside your config.
Here is an example where I have a custom modifier that showcases the result: https://play.tailwindcss.com/X74ERwVrHb

**Comment by lloydjatkinson** [comment]
How would we simply turn them off in the config? eg our sites are made of markdown converted to HTML at build time

**Comment by nkilm** [comment]
@RobinMalfait Thank you for providing the solution, it does remove the quotes. But it also removes some of the CSS properties i.e it removes the margins defined in prose class. How can I fix this?

**Comment by NatoBoram** [comment]
I'm trying to write this in Tailwind for the sake of it instead of making a new class and this is what I've come up with:
```html
<div class="before:prose-p:content-none after:prose-p:content-none" />
```
I haven't been able to fit `first-of-type` and `prose-blockquote`, but maybe someone else will

**Comment by terlan4** [comment]
@mathieutu where should i exactly put those rules? I couldn't figure it out.

**Comment by terlan4** [comment]
@RobinMalfait I have the same config, but it didnt work. and I am not getting any errors or anything. I am using Next.js

**Comment by raymondluong** [comment]
@terlan4 put it in `tailwind.config.js`, like this:

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            'blockquote p:first-of-type::before': false,
            'blockquote p:first-of-type::after': false,
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    // ...
  ],
}
```

https://tailwindcss.com/docs/typography-plugin#customizing-the-css

**Comment by jondcoleman** [comment]
This seems to work also:
```
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            blockquote: {
              quotes: "none",
            },
          },
        },
      },
    },
  },
```

**Comment by domdomegg** [comment]
For tailwind v4, you can do this in your `globals.css` (or wherever you have your `@import "tailwindcss";` directive):

```css
@utility prose {
    blockquote {
        /* Disable adding quote marks to block-quotes: https://github.com/tailwindlabs/tailwindcss-typography/issues/66 */
        p {
            &:first-of-type::before,
            &:last-of-type::after {
                content: none;
            }
        }
    }
}
```

**Comment by ryanagillie** [comment]
If you want to do it inline with v4, I think this should work:
```
prose-blockquote:[&>p]:first-of-type:before:content-none prose-blockquote:[&>p]:last-of-type:after:content-none
```
(I didn't want to change it globally)
