### ISSUE TITLE
list entry with line break is styled in a strange way (in firefox)

### ISSUE THREAD

**Issue by violoncelloCH** [tailwindlabs/tailwindcss-typography#68]
for `<li>` elements which include line break(s) `<br>` the bullet or number goes to the correct position but the text is too far down and two far apart in firefox... in Chromium it looks correct

| firefox | chromium |
|----------|---------------|
| ![image](https://user-images.githubusercontent.com/22591354/92008466-80f19b80-ed47-11ea-8715-056ffa7b7cd8.png) | ![image](https://user-images.githubusercontent.com/22591354/92014389-73d8aa80-ed4f-11ea-9942-510d2f258cb5.png) |

**Comment by LostKobrakai** [comment]
Seems like `.prose > ul > li > :last-child` and `.prose > ul > li > :first-child` margins are applied to the `<br>` element. It seems to be fixed with adding `:not(br)`.

**Comment by violoncelloCH** [comment]
interesting find @LostKobrakai 
this makes sense, so I opened a PR with the changes: #91

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Wrote more information about it here: https://github.com/tailwindlabs/tailwindcss-typography/pull/91#issuecomment-756847575
