### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by pspeter3** [tailwindlabs/tailwindcss-typography#69]
Given that the typography sets colors for elements, how should those colors change with the new experimental dark mode?

**Comment by pspeter3** [comment]
I followed @stefanzweifel's article https://stefanzweifel.io/posts/2020/07/20/add-dark-mode-support-to-at-tailwindcsstypography/. Instead of adding a `dark` as a theme, you need to add `dark` as a variant for the typography plugin.

**Comment by dkast** [comment]
Hi, @pspeter3 do you think you could share your dark variant config of your `tailwind.config.js`? I'm kinda lost with this, an example would be very helpful. Thanks!

**Comment by stefanzweifel** [comment]
@dkast Author of that blog post here. Here's an example `tailwind.config.js` where you configure both light and dark version of the typography plugin.

Light settings go to `default`.
Dark settings go to `dark`.

```js
module.exports = {
    theme: {

        typography: (theme) => ({
            default: {
                css: {
                    color: theme('colors.gray.900'),

                    a: {
                        color: theme('colors.blue.500'),
                        '&:hover': {
                            color: theme('colors.blue.700'),
                        },
                    },
                },
            },

            dark: {
                css: {
                    color: theme('colors.gray.100'),

                    a: {
                        color: theme('colors.blue.100'),
                        '&:hover': {
                            color: theme('colors.blue.100'),
                        },
                    },
                },
            },
        }),

    },

    plugins: [
        require('@tailwindcss/typography')({
            modifiers: [],
        }),
    ]
}
```

**Comment by dkast** [comment]
@stefanzweifel awesome, thank you!

**Comment by pspeter3** [comment]
I think as an extension, if you want to use the experimental `darkModeVariant`, you likely want to add the following to your config:

```js
{
  variants: {
    typography: ["responsive", "dark"]
  }
}
```

**Comment by pspeter3** [comment]
I am curious though what the Tailwind team thinks the right colors for text should be in dark mode. I suspect it will depend on the new color palette as well.

**Comment by vinayakkulkarni** [comment]
```js
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  experimental: {
    darkModeVariant: true,
  },
  dark: 'class',
  future: {
    defaultLineHeights: true,
    standardFontWeights: true,
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
  theme: {
    extend: {
      colors: {
        twitter: '#1DA1F2',
        linkedIn: '#2867B2',
        github: '#333333',
        ...defaultTheme.colors,
      },
      fontFamily: {
        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
    },
    typography: (theme) => ({
      dark: {
        css: {
          color: theme('colors.gray.100'),
          a: {
            color: theme('colors.blue.100'),
            '&:hover': {
              color: theme('colors.blue.100'),
            },
          },
        },
      },
    }),
  },
  plugins: [
    require('@tailwindcss/ui'),
    require('@tailwindcss/custom-forms'),
    require('@tailwindcss/typography')({
      modifiers: [],
    }),
  ],
};
```
```html
      <article
        class="prose dark:prose-dark dark:text-gray-100"
      >
	  ...
	  </article>
```
Unfortunately, this doesn't seem to work!

I'm using color-mode nuxt module ( https://color-mode.nuxtjs.org/#tailwind-v18 )

**Comment by jhull** [comment]
Same problem here.

```
    typography: (theme) => ({
      default: {
        css: {
          color: theme('colors.gray-500')
        },
      }
```
is changing colors in light mode nicely (if I change above value), but under `dark` key nothing is changed (with `prose dark:prose-dark` as shown above).

Same setup with nuxt and color-mode module.

**Comment by benji014628** [comment]
okay valid but this is a feature request and a workaround would be 
`'@media (prefers-color-scheme: dark)': {
              h1: {
                color: '#d4d4d8',
              },
              h2: {
                color: '#d4d4d8',
              },
              a: {
                color: '#d4d4d8',
              },
              color: '#d4d4d8',
            },`

**Comment by chiefpansancolt** [comment]
Since the dark mode is now GA in 2.0 typography with prose should have a module apart that is configurable and documented on the usage of dark mode with it.

**Comment by Apostolique** [comment]
@vinayakkulkarni @jhull You forgot to enable the variant:
```js
  variants: {
    extend: {
      typography: ['dark']
    }
  },
```

**Comment by MatthewCaseres** [comment]
agree that there should be documentation on the subject. I found a good config for 2.0 at the bottom of this closed issue: https://github.com/tailwindlabs/tailwindcss-typography/issues/94

**Comment by Bilal-io** [comment]
@benji014628 seems like extending typography works when you do DEFAULT capitalized. 
I am still trying to understand how to extend dark mode.

**Comment by benji014628** [comment]
@benji014628 well with TailwindCSS 2.0 you need to do that

**Comment by sw-yx** [comment]
swimming by to say that i completely failed at this - did all the recommended `variants` and `theme.typography.dark.css` stuff and it JUST. REFUSED. TO. WORK. and i had no idea how to debug.

i ended up just throwing out the typography plugin altogether and [replacing with @applys](https://gist.github.com/sw-yx/94dd45a08220e1538c8915b6550c65d6).

if anyone here is frustrated by this undocumented support, know that you are not alone. when a thing hurts more than it helps then we shouldnt keep it around.

**Comment by MatthewCaseres** [comment]
```js
module.exports = {
  darkMode: "class",
  purge: ["./pages/**/*.js", "./pages/**/*.tsx", "./components/**/*.tsx", "./components/**/*.js"],
  theme: {
    extend: {
      colors: {
        dark: "#24283b",
      },

      typography: (theme) => ({
        DEFAULT: {
          css: {
            color: theme("colors.gray.900"),
            a: {
              color: theme("colors.blue.700"),
              "&:hover": {
                color: theme("colors.blue.700"),
                textDecoration: "none",
              },
            },
            "h2 a": {
              color: theme("colors.gray.900"),
              textDecoration: "none",
            },
            ".tag a": {
              textDecoration: "none",
            },
          },
        },

        dark: {
          css: {
            color: "white",
            a: {
              color: "#9ECE6A",
              "&:hover": {
                color: "#9ECE6A",
              },
            },

            "h2 a": {
              color: "#A9B1D6",
            },

            h1: {
              color: "#A9B1D6",
            },
            h2: {
              color: "#A9B1D6",
            },
            h3: {
              color: "#A9B1D6",
            },
            h4: {
              color: "#A9B1D6",
            },
            h5: {
              color: "#A9B1D6",
            },
            h6: {
              color: "#A9B1D6",
            },

            strong: {
              color: "#A9B1D6",
            },

            code: {
              color: "#A9B1D6",
            },

            figcaption: {
              color: theme("colors.gray.500"),
            },
            blockquote: {
              color: "white",
            },

            "::selection": {
              backgroundColor: "#6f7bb635",
            },
          },
        },
      }),
    },
  },
  variants: {
    extend: {
      typography: ["dark"],
    },
  },
  plugins: [require("@tailwindcss/typography')],
};
```
using this config on a site with tailwind 2.0. Comes from a closed issue in this repo i referenced in a previous comment.

**Comment by MildTomato** [comment]
Also came here wondering if tailwind2.0 dark mode support was officially supported with this plugin ?

**Comment by adamwathan** [comment]
Haven't added it by default but it's 100% possible to add with all of the existing options in Tailwind + the plugin. Here's a quick 5 minute version:

https://play.tailwindcss.com/xTOjz3kR3m?file=config

**Comment by kripod** [comment]
@adamwathan Thank you for providing clear instructions about how it should be done. Based on that, I’ve just opened #122 to address this issue for everyone. _(Docs are yet to be added.)_

**Comment by MildTomato** [comment]
I have a feeling it wasn't working for me because i didn't have the following imports in CSS

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

I was hoping to use this only importing the css classes required for typography.

**Comment by Bilal-io** [comment]
I got it to work.
Here is a working solution https://github.com/Bilal-io/bilalkhoukhi.com
prose and dark:prose-dark are applied in the post-layout.tsx
Theme switcher is in the header.tsx

**Comment by 10thfloor** [comment]
> Haven't added it by default but it's 100% possible to add with all of the existing options in Tailwind + the plugin. Here's a quick 5 minute version:
> 
> https://play.tailwindcss.com/xTOjz3kR3m?file=config
> 
> The steps to do this were:
> 
> 1. Enable dark mode in Tailwind, documented here: https://tailwindcss.com/docs/dark-mode
> 2. Add a "light" text modifier for the plugin, documented here: https://github.com/tailwindlabs/tailwindcss-typography#adding-new-modifiers
> 3. Enable the "dark" variant for the typography plugin, documented here: https://tailwindcss.com/docs/dark-mode#enabling-for-other-utilities

Thank you for all you do. I nearly quit my job trying to figure this out ;)

**Comment by gildesmarais** [comment]
> Haven't added it by default but it's 100% possible to add with all of the existing options in Tailwind + the plugin. Here's a quick 5 minute version:
> 
> [...]

Thank you for the step by step instructions. I feel these steps should be mentioned in README instead of being tucked away in a comment inside this issue. Tailwind lists "dark mode" as core concept and thus the typography plugin should make that core concept easy to adapt.

**Comment by pspeter3** [comment]
I added a quick PR for the documentation in case that's helpful @adamwathan

**Comment by jjranalli** [comment]
Just wanted to let everyone know that you can also use [Nightwind](https://github.com/jjranalli/nightwind) to easily manage the dark mode in Typography.

You can define every single color, or just let it automatically generate a dark mode for you (which should be fine in most cases).

[Relevant section of the docs](https://github.com/jjranalli/nightwind#typography)

**Comment by vesper8** [comment]
I've been using the solution proposed by Adam above and it seems to work very well, but today I opened the website in Facebook's embedded browser and the colours were quite wrong. It looks good in every other browser I've tried

**Comment by dimitarrusev** [comment]
Tried every possible example, still can't make it work. JIT or no JIT, all the same, dark mode styles are not applied...

**Comment by vidhanio** [comment]
How would this work in terms of the new Tailwind 3.0?

**Comment by pspeter3** [comment]
Per #216, I think you use `dark:prose-invert`?

**Comment by vidhanio** [comment]
Wow, completely missed that. That cut my className length by at least 200 characters 😄, thanks a ton!

**Comment by adamwathan** [comment]
Gonna close this I guess 😅 Enjoy!

**Comment by beeman** [comment]
Thanks @adamwathan and the rest of the team! 🎉

There's even a video on how to use it! 

https://www.youtube.com/watch?v=GEYkwfYytAM

**Comment by danjac** [comment]
I don't think the `dark:prose-invert` solution works with the typography version currently bundled with latest Tailwind standalone.

**Comment by rjitsu** [comment]
> 

+1 on that. 

> I don't think the `dark:prose-invert` solution works with the tailwindcss/typography version currently bundled with latest Tailwind standalone.

**Comment by danjac** [comment]
I've made a separate bug report for the standalone issue:

https://github.com/tailwindlabs/tailwindcss-typography/issues/233
