### ISSUE TITLE
The `start` attribute of the ordered list is ignored

### ISSUE THREAD

**Issue by neupauer** [tailwindlabs/tailwindcss-typography#71]
The `start` attribute of the ordered list ( [MDN | The Ordered List element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol) ) is ignored (reset).

```html
<ol start="4">

</ol>
```

**Reason:**
```js
ol: {
  counterReset: 'list-counter',
},
```

**Possible solution in future (maybe):**
```js
ol: {
  counterReset: 'list-counter attr(start number, 0)',
},
```

But `<type-or-unit>` param for `attr()` is not supported today. Solution like https://github.com/tailwindlabs/tailwindcss-typography/issues/70 is not possieble due to `start` is not finite. Does anyone have an idea?

EDIT:
Maybe option to opt-in/out for custom/default list style option?

There is also an issue ( https://github.com/tailwindlabs/tailwindcss-typography/issues/56 ), where both are rendered  - but it can illustrate what I mean, an option to enable/disable one of them.

**Comment by sw-yx** [comment]
just ran into this today. we need some sort of opt out, or to fix this underlying issue!

**Comment by neupauer** [comment]
In my opinion, the best solution right now is to display the default browser counter, and style it with the new pseudo-element `::marker` (supported in all modern browsers).

Overriding the default counter introduce several issues:

- `<ol>` attributes `reversed`, `start` and `type` are ignored
- `<ul>` attribute `type` is ignored *(`type` is deprecated, so not such an issue )*
- `<li>` attributes `type` and `value` are ignored *(`type` is deprecated, so not such an issue )*

> *I will prepare a PR*

Links:
[web.dev | `::marker`](https://web.dev/css-marker-pseudo-element/)

**Comment by mfullbrook** [comment]
I've run into this issue too.  It's a real problem when using markup that's been converted from markdown - markdown uses the `start` attribute when putting code blocks between ordered list items.

**Comment by sw-yx** [comment]
@adamwathan @simonswiss would you take a PR for this one?

**Comment by neupauer** [comment]
I have also prepared an alternative solution to this issue ( see PR https://github.com/tailwindlabs/tailwindcss-typography/pull/85 ) - If someone needs a quick solution, it seems to be a pretty good alternative
