### ISSUE TITLE
Whitelisting

### ISSUE THREAD

**Issue by mikebronner** [tailwindlabs/tailwindcss-typography#74]
I was wondering how I should whitelist unordered and ordered list styles. I tried:
```
        options: {
            whitelist: [
                'ol',
                'ul',
                'li',
                'li::before',
                'ol > li',
                'ol > li::before',
                'ul > li',
                'ul > li::before',
            ],
        },
```

in an attempt to cover all the bases, but this didn't seam to work. Any suggestions welcome! :)

Thanks!

**Comment by benji014628** [comment]
....

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

I am assuming that you want to `safelist` those classes so that those are kept when using purgecss?

Look at the safelist option here: https://tailwindcss.com/docs/optimizing-for-production#purge-css-options
