### ISSUE TITLE
Line-height of default text

### ISSUE THREAD

**Issue by FoxtrotCZ** [tailwindlabs/tailwindcss-typography#76]
Hello,
in prose css, line-height is set as:
.prose {
  font-size: 1rem;
  line-height: 1.75;
}

but in Tailwind it's
.text-base {
  font-size: 1rem;
  line-height: 1.5rem;
}

I think it should be set the same at 1.5rem.

Thanks.

**Comment by adamwathan** [comment]
This is by design so that long-form text is easier to read. Free to customize this as you see fit in your config file though 👍 

Thanks!
