### ISSUE TITLE
Table formatting not applied when using different typography sizes

### ISSUE THREAD

**Issue by fabge** [tailwindlabs/tailwindcss-typography#80]
When using `prose-xl` or any of the other sizes (other than `prose`), the table formatting is lost.
See below screenshots for an example.

Using `prose`:
![grafik](https://user-images.githubusercontent.com/21140791/96897446-e41dc580-148e-11eb-9677-fb85f96570bb.png)

Using `prose-xl`
![grafik](https://user-images.githubusercontent.com/21140791/96897526-f8fa5900-148e-11eb-81e7-e326b50a3d91.png)

**Comment by jsphpl** [comment]
Did you add assign only the `prose-xl` class? 

https://github.com/tailwindlabs/tailwindcss-typography#size-modifiers states:
> Size modifiers are designed to be used with the multi-class modifier pattern and must be used in conjunction with the base prose class:

```html
<!-- Will not work -->
<article class="prose-lg">
  {{ markdown }}
</article>

<!-- Always add the `prose` class -->
<article class="prose prose-lg">
  {{ markdown }}
</article>
```

**Comment by fabge** [comment]
Oh I guess, that's what I was missing 🤦‍♂️ thanks!
