### ISSUE TITLE
Modifier not working in removing styles...

### ISSUE THREAD

**Issue by terryupton** [tailwindlabs/tailwindcss-typography#81]
I am not sure if the `modifiers: []` only get taken into account when purging? Or should this remove it from the development build? As I am still seeing them all in there...?

I have setup a little test here to illustrate this.
https://play.tailwindcss.com/GVdcbyomgT

**Comment by adamwathan** [comment]
You’re including the plugin twice since it’s already included in the UI plugin. Instead pass your typography config to the UI plugin as an argument under the “typography” key.

(On phone so can’t easily type the full example sorry)

**Comment by adamwathan** [comment]
require(“@tailwindcss/ui”)({ typography: ... })

**Comment by terryupton** [comment]
Have tried it like so:
```
    require('@tailwindcss/ui')({ 
      typography: { modifiers: ['lg'] } 
    }),
```

But still no joy. Not sure my syntax is correct. is this documented anywhere?
Thanks @adamwathan

**Comment by terryupton** [comment]
Hey @adamwathan any ideas on how to remove these modifiers?
Thanks.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I would recommend you to upgrade to Tailwind 2.x, then you don't need the `@tailwindcss/ui` plugin anymore. You can then use the `typography` plugin directly like this:

```js
module.exports = {
  // ...
  plugins: [
    require('@tailwindcss/typography')({
      modifiers: [] // Removes all modifiers
    })
  ]
}
```

More information about upgrading can be found here: https://tailwindui.com/changes-for-v2
