### ISSUE TITLE
Blockquotes not displaying correctly in Chrome

### ISSUE THREAD

**Issue by alexzherdev** [tailwindlabs/tailwindcss-typography#83]
macOS 10.14.6
Chrome 86.0.4240.111

Not sure if this is a browser bug like https://github.com/tailwindlabs/tailwindcss/issues/1402. (I can also file this under tailwindcss if more appropriate) Essentially blockquotes are rendering as italic with regular weight 400 (not 500 as per the styles). This is with the standard SF NS font.
![image](https://user-images.githubusercontent.com/93752/97067510-bf028300-1572-11eb-8909-4d866d195e8f.png)

Noticed this while comparing with iOS where the blockquotes are noticeably bolder than regular text. Desktop Firefox and Safari also render a proper bold italic.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I don't think this is still applicable. Here is a reproduction that renders just fine for me (font weight 500 and italic, as defined in the styles): https://play.tailwindcss.com/CcUv7enpCH
