### ISSUE TITLE
<pre> is not responsive

### ISSUE THREAD

**Issue by milindvishnoi** [tailwindlabs/tailwindcss-typography#96]
```<pre> is not mobile responsive.```

![image](https://user-images.githubusercontent.com/48028572/99888484-32cba480-2c73-11eb-8910-fafef92db36c.png)

**Comment by benji014628** [comment]
umm repo?

**Comment by milindvishnoi** [comment]
@benji014628 Please check out [this PR](https://github.com/utm-cssc/website/pull/86)

**Comment by jasikpark** [comment]
A reasonable default for pre's would be overflow-x-auto, no?

**Comment by milindvishnoi** [comment]
@jasikpark, that works thanks!

**Comment by jasikpark** [comment]
How did you fix your problem? Isn't this something that should be added to tailwind-typography?

**Comment by milindvishnoi** [comment]
So for me, my project is using prism for something (idk why tho), which overrides the tailwind typography classes.

Therefore, I think tailwind typography is okay.

**Comment by jasikpark** [comment]
Ah, I see!

**Comment by vhscom** [comment]
There's a horizongal overflow issue when a `pre` exists within `prose` content in typography `0.5.0` when used with tailwind `3.0.15`. It looks just as OP describes. And it has nothing to do with Prism.

The issue occurs when the user attempts to center prose content by wrapping in inside a `grid` or `flex` container in order to center-align content. To avoid this issue users can align prose content by not using `flex` or `grid` to align prose content and instead using `prose mx-auto`.

**Comment by vhscom** [comment]
There's a horizongal overflow issue when a `pre` exists within `prose` content in typography `0.5.0` when used with tailwind `3.0.15`. It looks just as OP describes. And it has nothing to do with Prism.

The issue occurs when the user attempts to center prose content by wrapping in inside a `grid` or `flex` container. To avoid this issue users can center-align prose content by not using `flex` or `grid` and instead using `prose mx-auto`.

**Comment by vhscom** [comment]
There's a horizongal overflow issue when a `pre` exists within `prose` content in typography `0.5.0` when used with tailwind `3.0.15`. It looks just as OP describes. And it has nothing to do with Prism.

The issue occurs when the user attempts to center prose content by wrapping in inside a `grid` or `flex` container. To avoid this issue users can center-align prose content by not using `flex` or `grid` and instead using `prose mx-auto`. In order to reproduce the issue the `pre` must have at least one line of content that is long enough to trigger horizontal overflow.

**Comment by vhscom** [comment]
There's a horizongal overflow issue when a `pre` exists within `prose` content in typography `0.5.0` when used with tailwind `3.0.15`. It looks just as OP describes. And it has nothing to do with Prism.

The issue occurs when the user attempts to center prose content by wrapping in inside a `grid` or `flex` container. To avoid this issue users can center-align prose content by not using `flex` or `grid` and instead using `prose mx-auto`. To reproduce the issue the `pre` must have at least one line of content that is long enough to trigger horizontal overflow.

**Comment by vhscom** [comment]
There's a horizontal overflow issue when a `pre` exists within `prose` content in typography `0.5.0` when used with tailwind `3.0.15`. It looks just as OP describes. And it has nothing to do with Prism.

The issue occurs when the user attempts to center prose content by wrapping in inside a `grid` or `flex` container. To avoid this issue users can center-align prose content by not using `flex` or `grid` and instead using `prose mx-auto`. To reproduce the issue the `pre` must have at least one line of content that is long enough to trigger horizontal overflow.

**Comment by vhscom** [comment]
There's a horizontal overflow issue when a `pre` exists within `prose` content in typography `0.5.0` when used with tailwind `3.0.15`. It looks just as OP describes. And it has nothing to do with Prism.

The issue occurs when the user attempts to center prose content by wrapping in inside a `grid` or `flex` container. To avoid this issue users can center-align prose content by not using `flex` or `grid` and instead using `prose mx-auto`. To reproduce the issue the `pre` must have at least one line of content that is long enough to trigger horizontal overflow on a mobile viewport.

**Comment by marcuspoehls** [comment]
In my case, I used a `grid sm:grid-cols-1` layout. This `sm:` breakpoint caused the overflow issue for me. I had to use `grid grid-cols-1` instead and things are working fine.

**Comment by jeffoxd** [comment]
still an issue to this date, is there a better way than doing those hacks by those two fine people above my comment?

**Comment by jeffoxd** [comment]
still an issue to this date, is there any chance of this changing? imo i found the best way to do it is to do `mx-auto`

**Comment by DancinParrot** [comment]
> In my case, I used a `grid sm:grid-cols-1` layout. This `sm:` breakpoint caused the overflow issue for me. I had to use `grid grid-cols-1` instead and things are working fine.

This works for me but it adds extra space between paragraphs which looks odd in my layout. Based on my understanding, `grid` stretches items by default, so it's not some margin or padding that you can just remove. As a result, this hacky way doesn't fit my use case.

During some of my testing, I came up with 2 alternative methods that sort of address this issue:
1. Set `prose-pre:text-wrap` which will wrap all text in code blocks. This may not be ideal if you want the more conventional scrollable code block.
2. Set `w-full` in your parent div containing housing the overflowing prose that is immediately after its flex parent. For example, here's my layout:
```html
<body class="dark:bg-zinc-800 min-h-screen flex flex-col">
    <!-- Below shows main, which is overflowing from its parent, the body tag -->
    <main class="max-w-app h-full grow mx-auto px-6 pb-4 pt-16">
        <!-- Content -->
    </main>
</body>
```
The aforementioned code produces the layout as shown in the image below, where content in main is overflowing from the body tag. Without a `w-full` tag, I suppose `main`'s width is not limited based on its parent, thereby allowing for overflowing.
<p align="center">
    <img width="369" height="338" alt="Image" src="https://github.com/user-attachments/assets/c5444be5-c7c9-46da-a6dc-e7009898d704" />
</p>

To address this, simply add `w-full` to `main` to set its width to 100% of its parent, or body in this case. As a result, when content in `pre` overflows, it will trigger `overflow-x-auto` which is already set in TailwindCSS Typography defaults.
